"""Real Chromium DOM + actual worker JS through worker-bridge.cjs, mocked Chrome/HTTP.
No login, real employer traffic, real PDF, or AI credits. Not live site certification.
"""
import asyncio, base64, json, tempfile, threading, http.server, shutil
from contextlib import suppress
from pathlib import Path
from playwright.async_api import async_playwright
ROOT=Path(__file__).resolve().parents[1]
EXT=ROOT/('browser-extension' if (ROOT/'browser-extension').exists() else 'extension')
RESULTS=ROOT/'test-results';RESULTS.mkdir(exist_ok=True)
async def main():
 proc=await asyncio.create_subprocess_exec('node',str(ROOT/'tests/worker-bridge.cjs'),stdin=asyncio.subprocess.PIPE,stdout=asyncio.subprocess.PIPE,limit=4*1024*1024)
 pending={};seq=0;passed=[];page_errors=[]
 async def reader():
  while line:=await proc.stdout.readline():
   v=json.loads(line);future=pending.pop(v['id'],None)
   if future:
    if v.get('error'):future.set_exception(RuntimeError(v['error']))
    else:future.set_result(v.get('result'))
 reader_task=asyncio.create_task(reader())
 async def call(**data):
  nonlocal seq
  seq+=1;data['id']=seq;f=asyncio.get_running_loop().create_future();pending[seq]=f
  proc.stdin.write((json.dumps(data)+'\n').encode());await proc.stdin.drain();return await asyncio.wait_for(f,15)
 def check(name,cond):
  assert cond,name;passed.append(name);print('PASS',name,flush=True)
 base='https://fixture.invalid'
 scripts=json.loads((EXT/'manifest.json').read_text())['content_scripts'][1]['js']
 async with async_playwright() as p:
  browser=await p.chromium.launch(executable_path=shutil.which('chromium') or None,headless=True,args=['--no-sandbox','--disable-gpu']);ctx=await browser.new_context(viewport={'width':1280,'height':1000});ctx.set_default_timeout(5000)
  pages={};nextid=7
  async def bridge(source,msg):return await call(op='message',message=msg,sender={'tab':{'id':pages[source['page']]},'frameId':0,'url':await source['frame'].evaluate('__vjaLocation.href')})
  await ctx.expose_binding('workerBridge',bridge)
  chrome_mock="""(()=>{const listeners=[];window.chrome={runtime:{sendMessage:m=>window.workerBridge(m),onMessage:{addListener:f=>listeners.push(f)},getURL:p=>'chrome-extension://fixture/'+p,id:'fixture'},storage:{local:{get:async()=>({}),set:async()=>{},remove:async()=>{}},sync:{get:async()=>({})}}};window.dispatchExtensionMessage=m=>new Promise(resolve=>{let handled=false;for(const f of listeners){let sent=false;const r=f(m,{},v=>{sent=true;handled=true;resolve(v)});if(r===true){handled=true;break;}if(sent)break;}if(!handled)resolve(null)});})();"""
  async def open_page(path,inject=True,html=None,virtual_base=None,tab_id=None):
   nonlocal nextid
   pg=await ctx.new_page();nextid+=1;pages[pg]=tab_id if tab_id is not None else nextid;pg.on('pageerror',lambda e:page_errors.append(str(e)));
   virtual_base=virtual_base or base
   await pg.set_content('<base href="'+virtual_base+'/">'+(html if html else (ROOT/'tests/fixtures'/path.lstrip('/')).read_text()))
   await pg.evaluate('(url)=>{window.__vjaLocation=new URL(url)}',virtual_base+path)
   if inject:
    await pg.add_script_tag(content=chrome_mock)
    for script in scripts:await pg.add_script_tag(content=(EXT/script).read_text().replace('location.', '__vjaLocation.'))
    await pg.wait_for_timeout(250)
   return pg
  try:
   pdf=b'%PDF-1.4\n% fixture only; never use as a real CV\n%%EOF';file={'name':'english-fixture.pdf','type':'application/pdf','size':len(pdf),'base64':base64.b64encode(pdf).decode(),'savedAt':'fixture'}
   hh_vac=await open_page('/vacancy/123456',html='<html><body><form class=search><input name=text placeholder=\"Поиск вакансий\"></form><h1 data-qa=\"vacancy-title\">Junior .NET Developer</h1><div data-qa=\"vacancy-company-name\">Fixture</div><div data-qa=\"vacancy-description\">C# ASP.NET Core SQL REST</div><a data-qa=\"vacancy-response-link-top\" href=\"https://hh.ru/applicant/vacancy_response?vacancyId=123456\">Откликнуться</a></body></html>',virtual_base='https://hh.ru')
   check('HH vacancy with unrelated search form remains JOB_DESCRIPTION',await hh_vac.evaluate('vjaSiteAdapters.make().detectPageType()')=='JOB_DESCRIPTION')
   check('floating Apply appears automatically on HH vacancy without opening popup',await hh_vac.get_by_role('button',name='✦ Apply',exact=True).count()==1)
   await call(op='set',data={'cvVaultEn':file,'vjaCopilotSettings':{'aiConsent':False,'historyLimit':2}})
   pg=await open_page('/application.html');check('generic application detected',await pg.evaluate("vjaSiteAdapters.make().detectPageType()")=='APPLICATION_FORM')
   result=await pg.evaluate('vjaUniversal.prepare({open:false})');check('form prepared without submission',result.get('submitted') is False and await pg.evaluate('submits')==0)
   check('confirmed contact filled',await pg.locator('[name=email]').input_value()=='violettanicolaou@gmail.com')
   salary=await pg.locator('[name=salary]').input_value();check('unknown salary gets a neutral review draft while factual years stay empty',len(salary)>20 and ('обсуд' in salary.lower() or 'discuss' in salary.lower()) and await pg.locator('[name=years]').input_value()=='')
   check('legal consent stays unchecked',not await pg.locator('[name=consent]').is_checked())
   check('vacancy language selects the English CV without role-specific configuration',await pg.locator('[name=resume]').evaluate('(el)=>el.files[0]?.name')=='english-fixture.pdf')
   check('portfolio not overwritten with CV',await pg.locator('[name=portfolio]').evaluate('(el)=>el.files.length')==0)
   dev=await open_page('/dev-letter',html='<html><body><h1>Junior .NET Backend Developer</h1><div class=company-name>Fixture Tech</div><div class=job-description>C# ASP.NET Core REST API SQL Server Docker backend</div><form id=application><label>Email<input type=email name=email></label><label>Cover letter<textarea name=coverLetter></textarea></label><label>Resume<input type=file name=resume accept="application/pdf"></label><button type=submit>Submit application</button></form><script>window.submits=0;document.querySelector("form").addEventListener("submit",e=>{e.preventDefault();submits++});</script></body></html>');await dev.evaluate('vjaUniversal.prepare({open:false})');dev_letter=await dev.locator('[name=coverLetter]').input_value();check('developer cover letter is short project-focused, includes GitHub and excludes hospitality history','DentalClinic' in dev_letter and ('C#' in dev_letter or 'ASP.NET Core' in dev_letter) and 'github.com/ViolettaNcl' in dev_letter and 'Crowne' not in dev_letter and 'Front Desk' not in dev_letter and len(dev_letter)<900)
   await pg.locator('[name=email]').fill('existing@example.test');await pg.evaluate('vjaUniversal.prepare({open:false})');check('existing text preserved',await pg.locator('[name=email]').input_value()=='existing@example.test')
   records=await call(op='get');job=next(v for k,v in records['data'].items() if k.startswith('vjaApplicationJob:'));check('application in original storage with profile snapshot',bool(job['context']['profileSnapshot']['fullName']) and job['context']['status']=='Needs review')
   check('application timeline records preparation and review without claiming send',any(e.get('type')=='prepared' for e in job['context'].get('timeline',[])) and any(e.get('type')=='needs-review' for e in job['context'].get('timeline',[])))
   await pg.screenshot(path=str(RESULTS/'form-review.png'),full_page=True)
   # AI has no paid/external calls; the real worker receives mock HTTP results.
   chat=await open_page('/chat.html');check('chat identity and author detected',await chat.evaluate('vjaLiveChat.snapshot().conversationId')=='chat-A' and await chat.evaluate('vjaLiveChat.snapshot().latestInbound.includes("рассмотрим")'))
   await chat.evaluate('vjaLiveChat.openAiMenu()');check('AI menu exposes explicit full-dialog analysis action',await chat.get_by_role('button',name='🧠 Проанализировать весь диалог и ответить',exact=True).count()==1)
   await chat.get_by_role('button',name='Закрыть',exact=True).click()
   await chat.get_by_role('button',name='Спасибо, буду ждать',exact=True).click();default_reply=await chat.locator('textarea[name=message]').input_value();check('default feedback quick reply inserted with Telegram email and phone note',default_reply.startswith('Здравствуйте! Спасибо за ответ. Буду ждать обратной связи.') and '@Violet111' in default_reply and 'violettanicolaou@gmail.com' in default_reply and 'телефонному звонку могу не успеть ответить' in default_reply and await chat.evaluate('sends')==0)
   await chat.locator('textarea[name=message]').fill('My own draft');r=await chat.evaluate('vjaLiveChat.insertText("replacement",vjaLiveChat.snapshot())');check('chat draft overwrite requires explicit confirmation',r['code']=='existing' and await chat.locator('textarea[name=message]').input_value()=='My own draft')
   await chat.locator('textarea[name=message]').fill('');r=await chat.evaluate('vjaLiveChat.analyze()');check('background AI still requires consent unless user explicitly invokes current-chat analysis',r.get('code')=='consent-required')
   r=await chat.evaluate('vjaLiveChat.analyze("dialog","",true)');check('explicit current-chat AI works without forcing a settings detour',r.get('ok') is True)
   check('AI panel exposes full-answer vacancy-question and draft-polish tools',await chat.get_by_role('button',name='Ответить на все вопросы',exact=True).count()==1 and await chat.get_by_role('button',name='Вопрос работодателю',exact=True).count()==1 and await chat.get_by_role('button',name='Улучшить этот черновик',exact=True).count()==1)
   await chat.get_by_role('button',name='Вставить',exact=True).click();check('AI inserts never sends',(await chat.locator('textarea[name=message]').input_value()).startswith('Спасибо') and await chat.evaluate('sends')==0)
   await chat.screenshot(path=str(RESULTS/'chat-copilot.png'),full_page=True)
   # Real HH chat markup may not expose stable message data-qa attributes. The
   # DOM fallback must still read the active right-side dialogue instead of the chat list.
   hh_chat_html='''<html><body><div style="display:flex;height:850px"><aside style="width:330px"><h2>Чаты</h2><div>Разработчик C#</div><div>Менеджер</div></aside><main style="width:640px;padding:20px"><header><div>Adviya</div><div>Сейчас онлайн</div><div>Вакансия</div><h2>Специалист чат-поддержки</h2><a href="https://hh.ru/vacancy/999">Перейти</a></header><div class="plain-chat-area"><div class="plain-bubble" style="margin:40px 25px 20px 20px;padding:18px;background:#f3f4f8;border-radius:14px"><p>Здравствуйте! Это команда подбора Adviya. Коротко об условиях вакансии.</p><p>Задачи: консультация клиентов в чате и ведение истории общения в CRM.</p><p>Требование: знание азербайджанского языка.</p><p>Если условия подходят, напишите здесь несколько слов о себе.</p></div></div><form><textarea aria-label="Сообщение" placeholder="Сообщение" style="width:100%;height:70px"></textarea><button type="submit">Отправить</button></form></main></div></body></html>'''
   hh_chat=await open_page('/chat',html=hh_chat_html,virtual_base='https://hh.ru');hh_snap=await hh_chat.evaluate('vjaLiveChat.snapshot()');check('HH chat fallback reads dialogue even without stable message selectors',len(hh_snap.get('messages',[]))>0 and 'Если условия подходят' in ' '.join(m['text'] for m in hh_snap.get('messages',[])) and not hh_snap.get('latestInbound'))
   context_before=await chat.evaluate('vjaLiveChat.snapshot()');await chat.evaluate('switchThread()');r=await chat.evaluate('(s)=>vjaLiveChat.insertText("Wrong A reply",s)',context_before);check('old thread insertion rejected immediately',r.get('code')=='stale' and await chat.locator('textarea[name=message]').input_value()=='')
   await chat.wait_for_timeout(300);await chat.evaluate('dispatchExtensionMessage({type:"vjaCopilotPage",action:"command",command:"contacts-reply"})');check('hotkey command only inserts contacts', '@Violet111' in await chat.locator('textarea[name=message]').input_value() and await chat.evaluate('sends')==0)
   await chat.locator('textarea[name=message]').fill('');await chat.evaluate('dispatchExtensionMessage({type:"vjaCopilotPage",action:"command",command:"thank-you-reply"})');hot=await chat.locator('textarea[name=message]').input_value();check('thank-you hotkey inserts full default feedback reply without Send',hot.startswith('Здравствуйте! Спасибо за ответ.') and '@Violet111' in hot and 'violettanicolaou@gmail.com' in hot and await chat.evaluate('sends')==0)
   await chat.evaluate("switchThread('chat-A','support-1');document.querySelector('.incoming').textContent='Спасибо! Мы дадим обратную связь до пятницы.'");await chat.wait_for_timeout(300);await chat.evaluate("chrome.runtime.sendMessage({type:'vjaCopilot',op:'observe-chat',snapshot:vjaLiveChat.snapshot()})");state=await call(op='get');support_job=next(v for k,v in state['data'].items() if k.startswith('vjaApplicationJob:') and v.get('plan',{}).get('vacancyId')=='support-1');next_action=support_job.get('context',{}).get('nextAction');check('explicit recruiter deadline becomes a local next-action reminder',support_job.get('context',{}).get('status')=='Recruiter Replied' and next_action and next_action.get('type')=='feedback' and next_action.get('dueAt',0)>0)
   ext_sender={'url':'chrome-extension://fixture/home.html'};apps_payload=await call(op='message',message={'type':'vjaCopilot','op':'applications'},sender=ext_sender);check('popup analytics are derived from stored application history',apps_payload.get('ok') is True and apps_payload.get('analytics',{}).get('total',{}).get('applications',0)>=1 and apps_payload.get('analytics',{}).get('total',{}).get('response',0)>=1)
   app_id=support_job['plan']['id'];old_due=next_action['dueAt'];snoozed=await call(op='message',message={'type':'vjaCopilot','op':'next-action','id':app_id,'mode':'snooze','days':1},sender=ext_sender);check('next-action reminder can be snoozed without sending anything',snoozed.get('ok') is True and snoozed.get('application',{}).get('nextAction',{}).get('dueAt',0)>old_due and await chat.evaluate('sends')==0);done=await call(op='message',message={'type':'vjaCopilot','op':'next-action','id':app_id,'mode':'done'},sender=ext_sender);check('next-action can be marked done locally',done.get('ok') is True and done.get('application',{}).get('nextAction',{}).get('doneAt',0)>0)
   await call(op='set',data={'vjaWritingProvider':{'mode':'custom','endpoint':'http://127.0.0.1:43210/v1/chat/completions','model':'fixture-model','consent':True}})
   # Thread A request remains in flight while navigating to B.
   await chat.evaluate("switchThread('chat-A','support-1');document.querySelector('.incoming').textContent='SLOW_TEST расскажите о задачах';");await chat.wait_for_timeout(250)
   await chat.evaluate('()=>{window.slowResult=vjaLiveChat.analyze("neutral","",true);}');await chat.wait_for_timeout(150);await chat.evaluate('switchThread()');r=await chat.evaluate('window.slowResult');check('late Chat A response discarded in Chat B',r.get('code')=='stale' and await chat.get_by_label('Черновик ответа',exact=True).count()==0)
   # Strong IDs for multiple jobs; no title-only matching.
   await chat.evaluate("document.querySelector('main').removeAttribute('data-conversation-id');document.querySelector('main').removeAttribute('data-vacancy-id');document.querySelector('main a')?.remove();");await chat.evaluate('vjaLiveChat.scan()');check('AI pencil remains visible in old/unlinked active chat',await chat.get_by_role('button',name='✎ AI',exact=True).count()==1);r=await chat.evaluate('vjaLiveChat.analyze("dialog","",true)');check('old/unlinked active chat gets an AI draft without vacancy selection',r.get('ok') is True and r.get('code')!='needs-selection')
   # Floating Apply on a job-description page stays in-place and only shows compact status.
   ui=await open_page('/vacancy/auto-ui',html='<html><body><main data-job-id="auto-ui"><h1>Technical Support Specialist</h1><div class="company-name">Fixture Company</div><div class="job-description">Support customers and explain solutions clearly.</div></main></body></html>')
   await ui.evaluate("()=>{const real=chrome.runtime.sendMessage;chrome.runtime.sendMessage=async m=>m?.type==='vjaCopilot'&&m?.op==='auto-apply'?{ok:true,result:{submitted:true,status:'confirmed'},application:{id:'auto-ui'}}:m?.type==='vjaCopilot'&&m?.op==='vacancy-status'?{ok:true,applied:false}:real(m);}")
   ui_result=await ui.evaluate('vjaUniversal.autoApply()');check('floating Apply stays on current page and ends in confirmed compact state',ui_result.get('submitted') is True and await ui.evaluate('vjaUniversal.applyState')=='CONFIRMED' and await ui.get_by_role('button',name='✓ Отклик отправлен',exact=True).count()==1 and len(ctx.pages)>=1)
   # Explicit auto-apply is separate from safe preparation: only this direct user-selected mode may click final submit.
   auto=await open_page('/auto-application',html='<html><body><h1>Technical Support Specialist</h1><main data-job-id="auto-1"><div class="company-name">Fixture Company</div><div class="job-description">Support customers.</div><form id="application"><label>Email<input type=email name=email required></label><label>Cover letter<textarea name=coverLetter></textarea></label><button type=submit>Submit application</button></form></main><script>window.submits=0;document.querySelector("form").addEventListener("submit",e=>{e.preventDefault();window.submits++});</script></body></html>')
   prep=await auto.evaluate('vjaUniversal.prepare({open:false})');check('safe preparation path still does not submit before explicit auto action',prep.get('submitted') is False and await auto.evaluate('submits')==0)
   state=await call(op='get');auto_job=next(v for k,v in state['data'].items() if k.startswith('vjaApplicationJob:') and v.get('plan',{}).get('sourceUrl','').endswith('/auto-application'));auto_result=await auto.evaluate('(plan)=>vjaRunSiteApply(plan)',auto_job['plan']);check('explicit auto-apply path clicks final application control',await auto.evaluate('submits')==1 and auto_result.get('status') in ['clicked-unverified','confirmed'])
   # HH current-vacancy flow: response first, then dedicated cover-letter modal with generic «Отправить».
   hh_direct_html='''<html><body><h1 data-qa="vacancy-title">Technical Support Specialist</h1><div data-qa="vacancy-company-name">Fixture</div><div data-qa="vacancy-description">SaaS API SQL logs troubleshooting tickets</div><button id="respond">Откликнуться</button><section id="receipt" hidden><strong>Ваш отклик отправлен работодателю</strong><button id="attach">Приложить сопроводительное письмо</button></section><script>window.directLetter='';respond.addEventListener('click',()=>{receipt.hidden=false});attach.addEventListener('click',()=>{const d=document.createElement('div');d.setAttribute('role','dialog');d.innerHTML='<h2>Сопроводительное письмо</h2><textarea placeholder="Почему именно ваша кандидатура должна заинтересовать работодателя"></textarea><button>Закрыть</button><button id="sendCover">Отправить</button>';document.body.append(d);d.querySelector('#sendCover').addEventListener('click',()=>{window.directLetter=d.querySelector('textarea').value;d.remove()})});</script></body></html>'''
   hh_direct=await open_page('/vacancy/778',html=hh_direct_html,virtual_base='https://hh.ru');await hh_direct.evaluate('vjaUniversal.prepare({open:false})');state=await call(op='get');direct_job=next(v for k,v in state['data'].items() if k.startswith('vjaApplicationJob:') and v.get('plan',{}).get('sourceUrl','').endswith('/vacancy/778'));direct_plan=direct_job['plan'];direct_result=await hh_direct.evaluate('(plan)=>vjaRunSiteApply(plan)',direct_plan);check('HH current-vacancy Apply sends the dedicated cover letter after the resume response',await hh_direct.evaluate('window.directLetter')==direct_plan['coverLetter'] and direct_result.get('submitted') is True and direct_result.get('letterStepCompleted') is True and 'AppXite' not in direct_plan['coverLetter'] and 'Crowne' not in direct_plan['coverLetter'])
   kg_direct=await open_page('/vacancy/137861116?hhtmFrom=vacancy_search_list',html=hh_direct_html.replace('Technical Support Specialist','Специалист технической поддержки'),virtual_base='https://headhunter.kg');check('HeadHunter.kg vacancy is classified as HH job description',await kg_direct.evaluate("vjaSiteAdapters.make().provider==='hh' && vjaSiteAdapters.make().detectPageType()==='JOB_DESCRIPTION'"));check('floating Apply appears automatically on HeadHunter.kg without opening popup',await kg_direct.get_by_role('button',name='✦ Apply',exact=True).count()==1);await kg_direct.evaluate('vjaUniversal.prepare({open:false})');state=await call(op='get');kg_job=next(v for k,v in state['data'].items() if k.startswith('vjaApplicationJob:') and 'headhunter.kg/vacancy/137861116' in v.get('plan',{}).get('sourceUrl',''));kg_plan=kg_job['plan'];kg_result=await kg_direct.evaluate('(plan)=>vjaRunSiteApply(plan)',kg_plan);check('HeadHunter.kg Apply continues to cover-letter modal and clicks Send',await kg_direct.evaluate('window.directLetter')==kg_plan['coverLetter'] and kg_result.get('submitted') is True and kg_result.get('letterStepCompleted') is True and 'AppXite' not in kg_plan['coverLetter'] and 'Crowne' not in kg_plan['coverLetter'])
   legal=await open_page('/auto-legal',html='<html><body><h1>Technical Support Specialist</h1><main data-job-id="auto-legal-1"><div class="company-name">Fixture Company</div><div class="job-description">Support customers.</div><form id="application"><label>Email<input type=email name=email required></label><label>Cover letter<textarea name=coverLetter></textarea></label><label><input type=checkbox name=consent checked required> I agree to privacy terms</label><button type=submit>Submit application</button></form></main><script>window.submits=0;document.querySelector("form").addEventListener("submit",e=>{e.preventDefault();window.submits++});</script></body></html>')
   await legal.evaluate('vjaUniversal.prepare({open:false})');state=await call(op='get');legal_job=next(v for k,v in state['data'].items() if k.startswith('vjaApplicationJob:') and v.get('plan',{}).get('sourceUrl','').endswith('/auto-legal'));legal_result=await legal.evaluate('(plan)=>vjaRunSiteApply(plan)',legal_job['plan']);check('explicit auto-apply pauses on prechecked unreviewed legal consent',await legal.evaluate('submits')==0 and legal_result.get('reason')=='manual-risk-fields')
   # A trusted native HH list-card click is allowed to complete the same card's cover letter inline.
   hh_html='''<html><body><div data-qa="vacancy-serp__vacancy" id="card"><a data-qa="serp-item__title" href="https://hh.ru/vacancy/777">Junior .NET Backend Developer</a><div data-qa="vacancy-serp__vacancy-employer">Fixture Tech</div><div data-qa="vacancy-serp__vacancy-address">Можно удалённо</div><p>C# ASP.NET Core REST API SQL Server Docker backend developer</p><button id="nativeApply">Откликнуться</button><div id="receipt" hidden>Вы откликнулись <button id="attach">Приложить письмо</button></div></div><script>window.sentLetter='';nativeApply.addEventListener('click',()=>{receipt.hidden=false});attach.addEventListener('click',()=>{const d=document.createElement('div');d.className='bloko-modal';d.innerHTML='<h2>Сопроводительное письмо</h2><textarea name="coverLetter" placeholder="Почему именно ваша кандидатура должна заинтересовать работодателя"></textarea><footer><button id="closeLetter">Закрыть</button><button id="sendLetter">Отправить</button></footer>';document.body.append(d);d.querySelector('#sendLetter').addEventListener('click',()=>{window.sentLetter=d.querySelector('textarea').value;d.remove()})});</script></body></html>'''
   hh=await open_page('/search/vacancy?text=.net',html=hh_html,virtual_base='https://hh.ru');await hh.get_by_role('button',name='Откликнуться',exact=True).click();
   await hh.wait_for_function("window.sentLetter && window.sentLetter.length>20",timeout=12000);sent_letter=await hh.evaluate('window.sentLetter');check('native HH list click attaches and sends a vacancy-specific cover letter without opening vacancy detail','DentalClinic' in sent_letter and 'github.com/ViolettaNcl' in sent_letter and len(ctx.pages)>=1)
   list_job=None
   for _ in range(30):
    state=await call(op='get');list_job=next((v for k,v in state['data'].items() if k.startswith('vjaApplicationJob:') and v.get('plan',{}).get('vacancyId')=='777'),None)
    if list_job and list_job.get('context',{}).get('status')=='Applied':break
    await asyncio.sleep(.1)
   check('native HH list quick apply stores submitted cover-letter memory',bool(list_job) and list_job.get('context',{}).get('status')=='Applied' and list_job.get('context',{}).get('coverLetterMemory',{}).get('submittedText')==sent_letter)
   # If HH refuses a late cover letter because the employer has already viewed the application,
   # Violetta must close only that modal automatically and return to the vacancy list without a retry/error state.
   hh_viewed_html='''<html><body><div data-qa="vacancy-serp__vacancy" id="viewedCard"><a data-qa="serp-item__title" href="https://hh.ru/vacancy/783">Специалист по обработке обращений</a><div data-qa="vacancy-serp__vacancy-employer">Fixture Viewed</div><p>Письменная поддержка пользователей, тикеты, CRM и база знаний.</p><button id="viewedNative">Откликнуться</button><div id="viewedReceipt" hidden>Вы откликнулись <button id="viewedAttach">Приложить письмо</button></div></div><script>window.viewedCloseCount=0;window.viewedSendCount=0;viewedNative.addEventListener('click',()=>{viewedReceipt.hidden=false});viewedAttach.addEventListener('click',()=>{const d=document.createElement('div');d.setAttribute('role','dialog');d.innerHTML='<h2>Сопроводительное письмо</h2><textarea placeholder="Сопроводительное письмо"></textarea><div id="viewedNotice"></div><button id="viewedClose">Закрыть</button><button id="viewedSend">Отправить</button>';document.body.append(d);d.querySelector('#viewedClose').addEventListener('click',()=>{window.viewedCloseCount++;d.remove()});d.querySelector('#viewedSend').addEventListener('click',()=>{window.viewedSendCount++;d.querySelector('#viewedNotice').textContent='Отклик уже просмотрен работодателем.'})});</script></body></html>'''
   hh_viewed=await open_page('/search/vacancy?text=already-viewed',html=hh_viewed_html,virtual_base='https://hh.ru');await hh_viewed.wait_for_timeout(500);await hh_viewed.get_by_role('button',name='✦ Отклик + письмо',exact=True).click();await hh_viewed.wait_for_function('window.viewedCloseCount===1',timeout=12000);check('HH already-viewed cover-letter rejection is closed automatically',await hh_viewed.get_by_role('dialog').count()==0 and await hh_viewed.evaluate('window.viewedSendCount')==1 and await hh_viewed.evaluate('window.viewedCloseCount')==1);await hh_viewed.get_by_role('button',name='✓ Уже просмотрен',exact=True).wait_for(timeout=5000);check('already-viewed vacancy returns to list in a terminal non-error state',await hh_viewed.get_by_role('button',name='✓ Уже просмотрен',exact=True).count()==1 and await hh_viewed.get_by_role('button',name='! Повторить',exact=True).count()==0);state=await call(op='get');viewed_job=next(v for k,v in state['data'].items() if k.startswith('vjaApplicationJob:') and v.get('plan',{}).get('vacancyId')=='783');check('already-viewed result is recorded as Viewed without claiming the cover letter was sent',viewed_job.get('context',{}).get('status')=='Viewed' and viewed_job.get('result',{}).get('result',{}).get('employerAlreadyViewed') is True and viewed_job.get('result',{}).get('result',{}).get('coverLetterFilled') is False and any(e.get('type')=='hh-employer-viewed' for e in viewed_job.get('context',{}).get('timeline',[])))
   # Card-level one-click selection: Violetta injects a compact action beside the native HH response button.
   # This fixture covers the alternative HH flow where the cover letter is mandatory BEFORE the response is submitted.
   hh_required_html='''<html><body><div data-qa="vacancy-serp__vacancy" id="cardRequired"><a data-qa="serp-item__title" href="https://hh.ru/vacancy/779">Специалист технической поддержки</a><div data-qa="vacancy-serp__vacancy-employer">Fixture Support</div><div data-qa="vacancy-serp__vacancy-address">Можно удалённо</div><p>SaaS API SQL логи тикеты интеграции техническая поддержка</p><button id="nativeApplyRequired">Откликнуться</button><div id="receiptRequired" hidden>Ваш отклик отправлен работодателю</div></div><script>window.requiredLetter='';nativeApplyRequired.addEventListener('click',()=>{const d=document.createElement('div');d.setAttribute('role','dialog');d.innerHTML='<h2>Отклик на вакансию</h2><textarea placeholder="Сопроводительное письмо"></textarea><button id="closeRequired">Закрыть</button><button id="submitRequired">Откликнуться</button>';document.body.append(d);d.querySelector('#submitRequired').addEventListener('click',()=>{window.requiredLetter=d.querySelector('textarea').value;d.remove();receiptRequired.hidden=false})});</script></body></html>'''
   hh_required=await open_page('/search/vacancy?text=support',html=hh_required_html,virtual_base='https://hh.ru');await hh_required.wait_for_timeout(500);check('HH list cards get a visible Violetta one-click action without opening vacancy detail',await hh_required.get_by_role('button',name='✦ Отклик + письмо',exact=True).count()==1);await hh_required.get_by_role('button',name='✦ Отклик + письмо',exact=True).click();await hh_required.wait_for_function("window.requiredLetter && window.requiredLetter.length>20",timeout=12000);required_letter=await hh_required.evaluate('window.requiredLetter');check('selected HH card is highlighted while its exact application is processed',await hh_required.locator('#cardRequired').evaluate("el=>el.classList.contains('vja-card-selected')"));check('mandatory pre-submit HH cover-letter modal is filled and submitted automatically',('тех' in required_letter.lower() or 'saas' in required_letter.lower() or 'api' in required_letter.lower()) and 'Crowne' not in required_letter and 'AppXite' not in required_letter)

   # The search page may have a large H1 like “Найдено 19 718 вакансий”. The selected
   # card identity must win; the search-page heading must never become the cover-letter title.
   multi_html='''<html><body><h1>Найдено 19 718 вакансий</h1><div data-qa="vacancy-serp__vacancy" id="customerCard"><a data-qa="serp-item__title" href="https://hh.ru/vacancy/780">Менеджер по работе с клиентами в чатах</a><div data-qa="vacancy-serp__vacancy-employer">CASH ART</div><p>Общение с клиентами по текущим заявкам в чате, поиск информации и решение вопросов.</p><button id="customerNative">Откликнуться</button></div><div data-qa="vacancy-serp__vacancy" id="bankCard"><a data-qa="serp-item__title" href="https://hh.ru/vacancy/781">Консультант Информационно-консультационный центр Банка</a><div data-qa="vacancy-serp__vacancy-employer">ФОРА-БАНК</div><p>Входящие обращения клиентов и консультирование по продуктам.</p><button id="bankNative">Откликнуться</button></div><div data-qa="vacancy-serp__vacancy" id="opsCard"><a data-qa="serp-item__title" href="https://hh.ru/vacancy/782">Специалист по автоматизации и внутренним сервисам</a><div data-qa="vacancy-serp__vacancy-employer">ИП Гузовский Никита Дмитриевич</div><p>Техническая поддержка. Настраивать программы, браузеры, почту, мессенджеры, телефонию и рабочие устройства.</p><button id="opsNative">Откликнуться</button></div><script>window.multiLetter='';function wire(btn){btn.addEventListener('click',()=>{const d=document.createElement('div');d.setAttribute('role','dialog');d.innerHTML='<h2>Отклик на вакансию</h2><textarea placeholder="Сопроводительное письмо"></textarea><button>Закрыть</button><button id="sendOne">Откликнуться</button>';document.body.append(d);d.querySelector('#sendOne').addEventListener('click',()=>{window.multiLetter=d.querySelector('textarea').value;d.remove()})})}wire(customerNative);wire(bankNative);wire(opsNative);</script></body></html>'''
   multi=await open_page('/search/vacancy?text=chat',html=multi_html,virtual_base='https://hh.ru');await multi.wait_for_timeout(500);check('each HH card gets its own fast apply control',await multi.get_by_role('button',name='✦ Отклик + письмо',exact=True).count()==3);check('each HH card gets an inline Analysis control',await multi.get_by_role('button',name='Analysis',exact=True).count()==3);await multi.locator('#customerCard').get_by_role('button',name='Analysis',exact=True).click();await multi.locator('#customerCard .vja-card-call-analysis').filter(has_text='✓ Без звонков').wait_for(timeout=5000);check('Analysis marks a chat-only vacancy green after full background read',await multi.locator('#customerCard .vja-card-call-analysis').get_attribute('data-state')=='no-calls');await multi.locator('#bankCard').get_by_role('button',name='Analysis',exact=True).click();await multi.locator('#bankCard .vja-card-call-analysis').filter(has_text='✕ Есть звонки').wait_for(timeout=5000);check('Analysis marks a vacancy with inbound calls red',await multi.locator('#bankCard .vja-card-call-analysis').get_attribute('data-state')=='calls');await multi.locator('#opsCard').get_by_role('button',name='Analysis',exact=True).click();await multi.locator('#opsCard .vja-card-call-analysis').filter(has_text='✓ Без звонков').wait_for(timeout=5000);ops_title=(await multi.locator('#opsCard .vja-card-call-analysis').get_attribute('title') or '');check('Analysis uses a verified full vacancy source before deciding',await multi.locator('#opsCard .vja-card-call-analysis').get_attribute('data-state')=='no-calls' and ('фоновой вкладке' in ops_title or 'HH API' in ops_title));check('Analysis does not confuse configuring telephony with a phone-call duty',await multi.locator('#opsCard .vja-card-call-analysis').get_attribute('data-state')=='no-calls');await multi.locator('#customerCard').get_by_role('button',name='✦ Отклик + письмо',exact=True).click();await multi.wait_for_function("window.multiLetter && window.multiLetter.length>20",timeout=12000);multi_letter=await multi.evaluate('window.multiLetter');check('selected list card produces a vacancy-specific letter instead of the search heading','Менеджер по работе с клиентами в чатах' in multi_letter and 'Найдено 19 718 вакансий' not in multi_letter);state=await call(op='get');multi_job=next(v for k,v in state['data'].items() if k.startswith('vjaApplicationJob:') and v.get('plan',{}).get('vacancyId')=='780');check('selected card application stores the exact full vacancy title and full-detail coverage',multi_job['context']['vacancy']['title']=='Менеджер по работе с клиентами в чатах' and multi_job['context']['evidenceAudit']['coverage']=='full-dom')
   # 3.9.10 persistent vacancy memory: the same job restores Analysis and application state without another click.
   repeat=await open_page('/search/vacancy?text=chat-again',html=multi_html,virtual_base='https://hh.ru');await repeat.wait_for_timeout(700);await repeat.locator('#customerCard .vja-card-call-analysis').filter(has_text='✓ Без звонков').wait_for(timeout=4000);check('repeated vacancy restores cached Analysis automatically by vacancy ID',await repeat.locator('#customerCard .vja-card-call-analysis').get_attribute('data-state')=='no-calls');viewed_repeat_html='''<html><body><div data-qa="vacancy-serp__vacancy" id="viewedRepeat"><a data-qa="serp-item__title" href="https://hh.ru/vacancy/783">Специалист по обработке обращений</a><div data-qa="vacancy-serp__vacancy-employer">Fixture Viewed</div><p>Письменная поддержка пользователей.</p><button>Откликнуться</button></div></body></html>''';viewed_repeat=await open_page('/search/vacancy?text=viewed-again',html=viewed_repeat_html,virtual_base='https://hh.ru');await viewed_repeat.locator('#viewedRepeat .vja-card-fast-apply').filter(has_text='✓ Уже просмотрен').wait_for(timeout=4000);check('returning to the list restores terminal application state without re-applying',await viewed_repeat.locator('#viewedRepeat .vja-card-fast-apply').get_attribute('data-state')=='done');await repeat.close();await viewed_repeat.close()
   # A quick-list click can navigate to a full HH questionnaire. The job is bound before navigation,
   # the form resumes in the same tab, fills confirmed facts, preserves unknown/legal fields, and never final-submits.
   form_tab_id=171;form_vacancy={'provider':'hh','url':'https://hh.ru/vacancy/784','vacancyId':'784','title':'Junior .NET Backend Developer','company':'Fixture Forms','description':'C# ASP.NET Core SQL REST remote','descriptionCoverage':'snippet','selectedFromList':True}
   prepared_form=await call(op='message',message={'type':'vjaCopilot','op':'quick-list-prepare','vacancy':form_vacancy},sender={'tab':{'id':form_tab_id},'frameId':0,'url':'https://hh.ru/search/vacancy?text=forms'});check('quick-list preparation is persisted before form navigation',prepared_form.get('ok') is True and prepared_form.get('application',{}).get('vacancy',{}).get('vacancyId')=='784')
   form_html='''<html><body><h1>Junior .NET Backend Developer</h1><form id="application" data-step="1"><label>First name<input name="firstName"></label><label>Email<input type="email" name="email"></label><label>Cover letter<textarea name="coverLetter"></textarea></label><label>Expected salary<input name="salary"></label><label>I agree to terms<input type="checkbox" name="consent"></label><label>Resume<input type="file" name="resume" accept="application/pdf"></label><button type="submit" id="finalSubmit">Submit application</button></form><script>window.submits=0;application.addEventListener('submit',e=>{e.preventDefault();window.submits++});</script></body></html>'''
   form_page=await open_page('/applicant/vacancy_response?vacancyId=784',html=form_html,virtual_base='https://hh.ru',tab_id=form_tab_id);await form_page.wait_for_function("document.querySelector('[name=email]').value.length>0",timeout=7000);await form_page.wait_for_function("document.querySelector('[name=resume]').files.length===1",timeout=7000);form_first=await form_page.locator('[name=firstName]').input_value();form_email=await form_page.locator('[name=email]').input_value();form_letter=await form_page.locator('[name=coverLetter]').input_value();check('navigated HH questionnaire auto-fills known profile fields',bool(form_first) and form_email=='violettanicolaou@gmail.com' and len(form_letter)>20);form_salary=await form_page.locator('[name=salary]').input_value();check('questionnaire auto-attaches selected CV, drafts salary, and leaves legal consent for review',await form_page.locator('[name=resume]').evaluate('(el)=>el.files[0]?.name')=='english-fixture.pdf' and len(form_salary)>20 and ('обсуд' in form_salary.lower() or 'discuss' in form_salary.lower()) and not await form_page.locator('[name=consent]').is_checked());check('automatic form continuation never presses final Submit',await form_page.evaluate('window.submits')==0)
   memory_state=await call(op='get');form_job=next(v for k,v in memory_state['data'].items() if k.startswith('vjaApplicationJob:') and v.get('plan',{}).get('vacancyId')=='784');check('form progress and unresolved fields are persisted in vacancy memory',form_job.get('context',{}).get('formMemory',{}).get('reviewCount')==2 and form_job.get('context',{}).get('formMemory',{}).get('filled',0)>=4);await form_page.close()
   back_html='''<html><body><div data-qa="vacancy-serp__vacancy" id="formCard"><a data-qa="serp-item__title" href="https://hh.ru/vacancy/784">Junior .NET Backend Developer</a><div data-qa="vacancy-serp__vacancy-employer">Fixture Forms</div><p>C# ASP.NET Core SQL REST remote</p><button>Откликнуться</button></div></body></html>'''
   back_page=await open_page('/search/vacancy?text=forms',html=back_html,virtual_base='https://hh.ru',tab_id=form_tab_id);await back_page.wait_for_timeout(800);await back_page.locator('#formCard .vja-card-fast-apply').filter(has_text='! Форма: 2 проверить').wait_for(timeout=4000);check('Back to vacancy list restores saved form progress instead of losing the card memory',await back_page.locator('#formCard .vja-card-fast-apply').get_attribute('data-state')=='review');await back_page.close()

   # Manual Fill in a list modal must reuse the exact selected card too, not the search page.
   await call(op='set',data={'vjaCopilotSettings':{'aiConsent':False,'historyLimit':24,'quickListCoverLetter':False,'floatingApplyMode':'auto','alwaysCoverLetter':True,'compactApplyStatus':True}})
   fill_html='''<html><body><h1>Найдено 19 718 вакансий</h1><div data-qa="vacancy-serp__vacancy" id="fillCard"><a data-qa="serp-item__title" href="https://hh.ru/vacancy/781">Консультант Информационно-консультационный центр Банка</a><p>Входящие обращения клиентов и поиск информации.</p><button id="fillNative">Откликнуться</button></div><script>fillNative.addEventListener('click',()=>{const d=document.createElement('div');d.setAttribute('role','dialog');d.innerHTML='<h2>Отклик на вакансию</h2><textarea name="coverLetter" placeholder="Сопроводительное письмо"></textarea><button>Откликнуться</button>';document.body.append(d)})</script></body></html>'''
   fill_page=await open_page('/search/vacancy?text=bank',html=fill_html,virtual_base='https://hh.ru');await fill_page.get_by_role('button',name='Откликнуться',exact=True).click();await fill_page.wait_for_timeout(250);fill_result=await fill_page.evaluate('vjaUniversal.prepare({open:false})');fill_letter=await fill_page.locator('textarea[name=coverLetter]').input_value();check('manual Fill in HH list modal uses the pinned vacancy rather than the search page','Консультант Информационно-консультационный центр Банка' in fill_letter and 'Найдено 19 718 вакансий' not in fill_letter and fill_result.get('submitted') is False);await fill_page.close();await multi.close()
   await call(op='set',data={'vjaCopilotSettings':{'aiConsent':False,'historyLimit':24,'quickListCoverLetter':True,'floatingApplyMode':'auto','alwaysCoverLetter':True,'compactApplyStatus':True}})
   # Minimal UI stays absent on unrelated pages; JSON-LD-only jobs use existing parser.
   unrelated=await open_page('/blank.html',html='<html><body><h1>Cooking notes</h1><p>Unrelated personal page.</p></body></html>');check('no UI on unrelated pages',await unrelated.locator('[data-vja-root]').count()==0)
   ld=await open_page('/jobs/structured',html='<html><body><h1>Structured role</h1><script type="application/ld+json">{"@type":"JobPosting","title":"QA Engineer","description":"<p>Test interfaces carefully.</p>","identifier":{"value":"qa-12"},"hiringOrganization":{"name":"Fixture Co"}}</script></body></html>');check('JSON-LD vacancy parsing',await ld.evaluate('vjaSiteAdapters.make().extractVacancy().description')=='Test interfaces carefully.')
   # Open shadow DOM fields and explicit steps are browser DOM operations.
   shadow=await open_page('/application-shadow',inject=False,html='<html><body><h1>QA Engineer</h1><div id="host"></div></body></html>');await shadow.evaluate("document.querySelector('#host').attachShadow({mode:'open'}).innerHTML='<form id=application><label>Email<input name=email type=email></label><button type=submit>Submit application</button></form>'")
   await shadow.add_script_tag(content=chrome_mock)
   for script in scripts:await shadow.add_script_tag(content=(EXT/script).read_text().replace('location.', '__vjaLocation.'))
   await shadow.evaluate('vjaUniversal.prepare({open:false})');check('open shadow DOM form fills',await shadow.locator('#host input').input_value()=='violettanicolaou@gmail.com')
   r=await call(op='get');ai_requests=[h for h in r['http'] if h['url'].endswith('/chat/completions')];check('AI payload includes vacancy snapshot CV version and latest message',any('applicationContext' in h['body'] and 'support-1' in h['body'] and 'CONFIRMED' in h['body'] and 'AppXite' in h['body'] for h in ai_requests));check('no final submission HTTP endpoint called',not any('apply-tailored' in h['url'] or 'browser-applied' in h['url'] or 'browser-auto-applied' in h['url'] for h in r['http']))
   # A safe multi-step button never becomes a final submit command.
   step=await open_page('/application-step',html='<html><body><h1>Junior Developer</h1><main data-job-id="step-1"><form id="application" data-step="1"><label>First name<input name="firstName"></label><button type="button" id="next">Next</button></form></main><script>window.submits=0;document.querySelector("form").addEventListener("submit",e=>{e.preventDefault();submits++});document.querySelector("#next").onclick=()=>{document.querySelector("form").innerHTML="<label>Email<input type=email name=email></label><button type=submit>Submit application</button>"};</script></body></html>')
   await step.evaluate('vjaUniversal.prepare({open:false})');await step.get_by_role('button',name='Следующий шаг',exact=True).click();await step.wait_for_timeout(700);check('explicit intermediate step fills next form without submit',await step.locator('[name=email]').input_value()=='violettanicolaou@gmail.com' and await step.evaluate('submits')==0)
   # Bound lazy-history loading merges older messages and restores scroll position.
   history=await open_page('/chat.html');await history.evaluate("()=>{const e=document.querySelector('.history');e.style.height='50px';e.scrollTop=e.scrollHeight;let loaded=false;e.addEventListener('scroll',()=>{if(e.scrollTop===0&&!loaded){loaded=true;const m=document.createElement('div');m.className='message';m.dataset.messageId='old-0';m.dataset.sender='employer';m.textContent='Интервью в 14:00, подтвердите время';e.prepend(m);}})}")
   hist=await history.evaluate('vjaLiveChat.loadHistory(vjaLiveChat.snapshot())');check('lazy history collects older messages without duplicates',len([m for m in hist['messages'] if m['id']=='old-0'])==1 and len(hist['messages'])==3)
   check('chat scroll restored after history read',await history.locator('.history').evaluate('(el)=>Math.abs(el.scrollHeight-el.scrollTop-el.clientHeight)<4'))
   # Release long-lived fixture pages before popup/settings checks; only HH chat is reused below.
   for old_page in list(ctx.pages):
    if old_page is not hh_chat: await old_page.close()
   # Render the real compact action popup and verify the new rocket agent is the primary autonomous control.
   import re
   home=await ctx.new_page();nextid+=1;pages[home]=nextid;home.on('pageerror',lambda e:page_errors.append('home: '+str(e)))
   home_markup=(EXT/'home.html').read_text();await home.set_content(re.sub(r'<script src="[^"]+"></script>','',home_markup));await home.add_script_tag(content=chrome_mock)
   await home.evaluate("""()=>{chrome.tabs={query:async()=>[{id:91,url:'https://hh.ru/search/vacancy?text=.net'}],sendMessage:async()=>({pageType:'JOB_LIST'}),create:async()=>{}};chrome.permissions={contains:async()=>true,request:async()=>true};chrome.storage.session={get:async()=>({vjaAutopilotSession:{count:0}}),remove:async()=>{}};chrome.storage.sync={get:async(arg)=>{if(Array.isArray(arg))return {vjaHhBrowserSearch:true};return {apiBase:'http://127.0.0.1:8080'};},set:async()=>{}};chrome.storage.local={get:async()=>({}),set:async()=>{},remove:async()=>{}};chrome.runtime.sendMessage=async m=>m?.type==='vjaCopilot'?(m.op==='applications'?{ok:true,applications:[],analytics:null}:{ok:true}):{ok:true};window.fetch=async()=>({ok:true,text:async()=>JSON.stringify({allowed:true,autoApplyEnabled:false,remainingToday:15,autoApplyMinimumScore:80,dailyAutoApplyLimit:15,appliedToday:0,lastMessage:''})});}""")
   await home.add_script_tag(content=(EXT/'home.js').read_text());await home.wait_for_timeout(200);check('compact home popup exposes the rocket autopilot with threshold/session/day status',await home.get_by_role('button',name='🚀 Запустить автопилот',exact=True).count()==1 and 'Порог 80/100' in await home.locator('#autopilotHomeStats').inner_text() and await home.locator('#primary').is_disabled())
   # Render the actual settings with storage/Chrome APIs mocked at the boundary.
   import re
   opt=await ctx.new_page();nextid+=1;pages[opt]=nextid;opt.on('pageerror',lambda e:page_errors.append('options: '+str(e)));opt.on('console',lambda m: print('OPTIONS CONSOLE',m.text,flush=True) if m.type in ['error','warning'] else None)
   markup=(EXT/'options.html').read_text();option_scripts=re.findall(r'<script src="([^"]+)"></script>',markup)
   await opt.set_content(re.sub(r'<script src="[^"]+"></script>','',markup));await opt.evaluate("()=>window.__vjaLocation=new URL('chrome-extension://fixture/options.html')")
   await ctx.expose_binding('readFixtureStorage',lambda source:call(op='get'))
   async def write_storage(source,data):return await call(op='set',data=data)
   await ctx.expose_binding('writeFixtureStorage',write_storage)
   await opt.add_script_tag(content=chrome_mock)
   await opt.evaluate("""()=>{chrome.storage.local.get=async()=> (await readFixtureStorage()).data;chrome.storage.local.set=writeFixtureStorage;chrome.storage.sync={get:async()=>({apiBase:'http://localhost:8080'}),set:async()=>{}};chrome.runtime.openOptionsPage=async()=>{};chrome.commands={getAll:async()=>[]};chrome.tabs={create:async()=>{},query:async()=>[]};chrome.scripting={getRegisteredContentScripts:async()=>[]};window.fetch=async()=>({ok:false,status:503,json:async()=>({}),text:async()=>''});}""")
   for script in option_scripts:await opt.add_script_tag(content=(EXT/script).read_text())
   await opt.wait_for_timeout(250);check('actual settings loads migrated contacts',await opt.locator('#cpTelegram').input_value()=='@Violet111')
   await opt.locator('#cpPhone').fill('+70000000000');await opt.locator('#cpSave').click();await opt.get_by_text('Сохранено. Открытые чаты обновятся автоматически или после обновления страницы.', exact=True).wait_for(timeout=3000);stored=await call(op='get');check('settings saves profile and shared legacy phone memory',stored['data']['vjaCandidateTruthProfile']['contacts']['phone']=='+70000000000' and stored['data']['applicationMemory']['phone']=='+70000000000')
   check('settings removed role-specific CV section',await opt.get_by_text('CV для конкретных ролей',exact=False).count()==0)
   check('settings exposes one configurable primary quick reply',await opt.locator('#cpReplies .cpReply').count()==1)
   check('settings exposes native HH list cover-letter toggle',await opt.locator('#cpQuickListCoverLetter').count()==1 and await opt.locator('#cpQuickListCoverLetter').is_checked())
   await opt.screenshot(path=str(RESULTS/'settings.png'))
   # 3.8 behavior, not merely the presence of buttons.
   check('memory UI shows imported CV HH provenance',await opt.locator('#truthMemory380').count()==1 and 'AppXite' in await opt.locator('#truthMemory380').text_content())
   check('model settings distinguish local facts from configured AI',await opt.locator('#writingProvider380').count()==1 and 'Без внешней модели' in await opt.locator('#writingProvider380').text_content())
   await call(op='set',data={'vjaWritingProvider':{'mode':'local'}})
   direct=await open_page('/chat.html');await direct.evaluate("document.querySelector('.incoming').textContent='Работали с API? Есть опыт с SQL?'");await direct.wait_for_timeout(200)
   await direct.get_by_role('button',name='✎ AI',exact=True).click();await direct.get_by_role('button',name='🧠 Проанализировать весь диалог и ответить',exact=True).click()
   await direct.get_by_label('Черновик ответа',exact=True).wait_for(timeout=4000);reply=await direct.get_by_label('Черновик ответа',exact=True).input_value()
   check('trusted analyze button answers actual API and SQL questions from current facts','API' in reply and 'SQL' in reply and not reply.startswith('Спасибо'))
   check('contextual technical reply omits unrelated hospitality and teaching',not any(x in reply for x in ['Crowne','Front Desk','преподав']))
   await direct.get_by_role('button',name='Вставить',exact=True).click();check('contextual reply insertion never clicks recruiter Send',await direct.evaluate('sends')==0 and await direct.locator('textarea[name=message]').input_value()==reply)
   await direct.screenshot(path=str(RESULTS/'chat-evidence-3.8.png'),full_page=True)
   # Candidate corrections do not change an immutable historical application profile.
   current=await call(op='get');p_before=current['data']['vjaCandidateTruthProfile'];assert p_before['seedRevision']=='2026-09-28.1'
   check('installed profile actually contains new AppXite and freelance evidence',any(f['id']=='exp-appxite' for f in p_before['facts']) and any(f['id']=='exp-freelance-dev' for f in p_before['facts']))
   # No content is not an AI success. Unknown evidence is shown separately.
   await direct.evaluate("document.querySelector('.incoming').textContent='Есть ли опыт с Jira?'");await direct.locator('textarea[name=message]').fill('');await direct.wait_for_timeout(200)
   r=await direct.evaluate('vjaLiveChat.analyze("dialog","",true)');check('unconfirmed Jira does not become a fabricated answer',not r.get('ok') and await direct.get_by_label('Черновик ответа',exact=True).count()==0)
   check('missing-fact reason is visible in the chat panel','Jira' in await direct.locator('body').inner_text() and await direct.evaluate('sends')==0)
   await direct.evaluate("document.querySelectorAll('[data-message-id]').forEach(e=>e.remove())");await direct.wait_for_timeout(200);r=await direct.evaluate('vjaLiveChat.analyze("dialog","",true)');check('empty active history is reported instead of a canned AI response',not r.get('ok') and await direct.get_by_label('Черновик ответа',exact=True).count()==0)
   # The ambiguous HH bubble can be explicitly attributed, never silently assumed.
   await hh_chat.evaluate("document.querySelector('.plain-bubble').innerHTML='<p>Работали с API и SQL?</p>'");await hh_chat.wait_for_timeout(200)
   r=await hh_chat.evaluate('vjaLiveChat.analyze("dialog","",true)');check('ambiguous sender requires a visible single-message confirmation',r.get('code')=='unknown-sender' and await hh_chat.get_by_role('button',name='Это сообщение работодателя — анализировать',exact=True).count()==1)
   await hh_chat.get_by_role('button',name='Это сообщение работодателя — анализировать',exact=True).click();await hh_chat.get_by_label('Черновик ответа',exact=True).wait_for(timeout=4000)
   check('confirmed HH sender unlocks a factual draft for the same active dialog','API' in await hh_chat.get_by_label('Черновик ответа',exact=True).input_value())
   check('HH sidebar conversations never enter read history',not any(m['text']=='Разработчик C#' or m['text']=='Менеджер' for m in (await hh_chat.evaluate('vjaLiveChat.snapshot()'))['messages']))
   # 3.9.10: a hidden HH tab may remain `loading` while its DOM is already readable.
   readable=await call(op='eval',code="cpReadVacancy('https://hh.ru/vacancy/785',{url:'https://hh.ru/search/vacancy'},{fast:true})")
   check('HH background reader accepts an interactive readable DOM without waiting for tab.status complete',readable.get('vacancyId')=='785' and readable.get('descriptionCoverage')=='full-dom')
   # If the live DOM cannot be read, the exact vacancy ID must fall back to api.hh.ru rather than a card snippet.
   api_fallback=await call(op='eval',code="cpCompleteVacancy({url:'https://hh.ru/vacancy/784',vacancyId:'784',title:'Специалист технической поддержки / Support L1',description:'snippet',descriptionCoverage:'snippet'},{url:'https://hh.ru/search/vacancy'},{embedded:true})")
   check('HH letter preparation falls back to full api.hh.ru vacancy data',api_fallback.get('vacancyId')=='784' and api_fallback.get('descriptionCoverage')=='full-fetch' and 'Телефонные звонки не требуются' in api_fallback.get('description',''))
   api_analysis=await call(op='eval',code="cpQuickListCallAnalysis({url:'https://hh.ru/vacancy/784',vacancyId:'784',title:'Специалист технической поддержки / Support L1',description:'snippet',descriptionCoverage:'snippet'},{tab:{id:7},frameId:0,url:'https://hh.ru/search/vacancy'})")
   check('Analysis uses HH API fallback and returns a confirmed no-calls result',api_analysis.get('source')=='hh-api' and api_analysis.get('status')=='no-calls' and api_analysis.get('canApply') is True)
   # Read failures must stop letter preparation, not use a vacancy-card snippet.
   failure=await call(op='eval',code="(async()=>{try{await cpCompleteVacancy({url:'https://hh.ru/vacancy/unreadable',title:'Backend Developer',description:'snippet',descriptionCoverage:'snippet'},{url:'https://hh.ru/search/vacancy'});return false;}catch(e){return e.message;}})()")
   check('missing full vacancy text blocks letter generation',isinstance(failure,str) and bool(failure))
   check('HH list sent letter is bound to full-description evidence audit',list_job['context']['evidenceAudit']['coverage'] in {'full-dom','full-fetch'} and list_job['context']['evidenceAudit']['factIds'])
   # Raw web/AI content cannot invoke the trusted profile import endpoint.
   denied=await call(op='message',message={'type':'vjaCopilot','op':'source-accept','facts':[{'id':'injected','text':'fake experience'}],'acceptedIds':['injected'],'source':{'id':'bad','type':'user-confirmed'}},sender={'tab':{'id':999},'frameId':0,'url':'https://hh.ru/vacancy/777'})
   after=await call(op='get');check('employer content cannot write candidate truth facts',not denied.get('ok') and not any(f['id']=='injected' for f in after['data']['vjaCandidateTruthProfile']['facts']))
   check('thread drafts are not promoted to global candidate history',len(after['data']['vjaCandidateTruthProfile']['facts'])==len(p_before['facts']))
   # Model transport sends exact active dialog plus evidence (the model is mocked).
   await call(op='set',data={'vjaWritingProvider':{'mode':'custom','endpoint':'http://127.0.0.1:43210/v1/chat/completions','model':'fixture-model','consent':True}})
   model_chat=await open_page('/chat.html');await model_chat.evaluate("document.querySelector('.incoming').textContent='Работали с API?'");await model_chat.wait_for_timeout(200)
   r=await model_chat.evaluate('vjaLiveChat.analyze("dialog","",true)');check('configured model path produces a validated contextual draft',r.get('ok') is True)
   evidence_text=await model_chat.locator('details').text_content();check('model result is visibly distinguished from local evidence output','AI-модель' in evidence_text)
   captured=(await call(op='get'))['http'];request_body=json.loads([h['body'] for h in captured if h['url'].endswith('/chat/completions')][-1]);payload=json.loads(request_body['messages'][1]['content'])
   check('model payload carries last employer question, candidate evidence and application identity',payload['latestRecruiterMessage']['text']=='Работали с API?' and payload['candidateFacts'] and payload['applicationContext']['conversationId']=='chat-A')
   check('no uncaught DOM JavaScript errors',not page_errors)
  finally:
   (RESULTS/'browser-e2e.json').write_text(json.dumps({'passed':passed,'count':len(passed),'pageErrors':page_errors,'boundary':'Offline Chromium DOM + actual worker JS; mocked Chrome APIs, HTTP and page URLs. MV3 load blocked by test-environment administrator policy; not certified live sites.'},ensure_ascii=False,indent=2));await browser.close();
   if proc.stdin and not proc.stdin.is_closing(): proc.stdin.close()
   if proc.returncode is None:
    proc.terminate()
    try: await asyncio.wait_for(proc.wait(),2)
    except asyncio.TimeoutError:
     proc.kill();await proc.wait()
   reader_task.cancel()
   with suppress(asyncio.CancelledError): await reader_task
 print(f'{len(passed)} browser integration assertions passed.',flush=True)
if __name__=='__main__':asyncio.run(main())
