// Test-only JSON-lines bridge. Real service worker code, fake Chrome/HTTP boundary.
const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),crypto=require('node:crypto');
const ROOT=path.resolve(__dirname,fs.existsSync(path.resolve(__dirname,'../browser-extension'))?'../browser-extension':'../extension');const data={},session={},sync={apiBase:'http://127.0.0.1:8080'},listeners=[],http=[],tabs=new Map();
const clone=x=>x===undefined?undefined:JSON.parse(JSON.stringify(x));
function storage(obj){return {get:async keys=>{if(keys==null)return clone(obj);if(typeof keys==='string')keys=[keys];if(Array.isArray(keys))return Object.fromEntries(keys.filter(k=>k in obj).map(k=>[k,clone(obj[k])]));return Object.fromEntries(Object.entries(keys).map(([k,v])=>[k,clone(obj[k]??v)]));},set:async x=>Object.assign(obj,clone(x)),remove:async keys=>[].concat(keys).forEach(k=>delete obj[k]),setAccessLevel:async()=>{}};}
const event={addListener:()=>{}},manifest=JSON.parse(fs.readFileSync(path.join(ROOT,'manifest.json')));let id=100;
const context={console:{log(){},warn(){},error(){}},URL,Date,Promise,Map,Set,Object,JSON,Uint8Array,btoa:s=>Buffer.from(s,'binary').toString('base64'),crypto:crypto.webcrypto,AbortController,setTimeout,clearTimeout,self:{},chrome:{runtime:{onInstalled:event,onStartup:event,onMessage:{addListener:f=>listeners.push(f)},getURL:p=>'chrome-extension://fixture/'+p,getManifest:()=>manifest,openOptionsPage:async()=>{}},alarms:{create:async()=>{},onAlarm:event},commands:{onCommand:event},permissions:{onRemoved:event,contains:async()=>true},scripting:{getRegisteredContentScripts:async()=>[],registerContentScripts:async()=>{},executeScript:async args=>{const tab=tabs.get(args?.target?.tabId);if(String(tab?.url||'').includes('/vacancy/785'))return [{result:{readyState:'interactive',hasBody:true,textLength:500}}];return [];}},storage:{local:storage(data),session:storage(session),sync:storage(sync)},tabs:{get:async n=>tabs.get(n),query:async()=>[...tabs.values()],create:async o=>{const t={id:++id,...o,status:String(o?.url||'').includes('/vacancy/785')?'loading':'complete'};tabs.set(t.id,t);return t;},remove:async n=>tabs.delete(n),sendMessage:async(n,m)=>{if(m.type==='vjaCopilotPage'&&m.action==='vacancy'){const url=tabs.get(n)?.url,id=new URL(url).pathname.split('/').pop();if(id==='unreadable'||id==='784')return {ok:false};const fixtures={
'779':{title:'Специалист технической поддержки',description:'Техническая поддержка SaaS-платформы: тикеты, API, SQL, логи, интеграции, диагностика и взаимодействие с разработчиками. Полное описание работодателя.'},
'780':{title:'Менеджер по работе с клиентами в чатах',description:'Общение с клиентами по текущим заявкам в чате, контроль статуса обращений, письменная коммуникация, поиск информации и решение вопросов. Полное описание работодателя.'},
'781':{title:'Консультант Информационно-консультационный центр Банка',description:'Принимать входящие звонки клиентов, консультировать по банковским продуктам и фиксировать результаты обращений. Полное описание работодателя.'},
'782':{title:'Специалист по автоматизации и внутренним сервисам',description:'Техническая поддержка сотрудников. Решать технические вопросы и доводить их до результата. Настраивать программы, браузеры, почту, мессенджеры, телефонию и рабочие устройства. Обязательно: опыт работы с CRM и облачными сервисами, практический опыт с API и скриптами, понимание интеграций между сервисами.'},
'785':{title:'Специалист технической поддержки / Support L1',description:'Регистрация обращений пользователей и партнеров. Консультирование по чатам, Telegram и Reddit. Работа с тикетами и базой знаний. Полное описание работодателя.'}
};const f=fixtures[id]||{title:'Junior .NET Backend Developer',description:'Разработка на C# и ASP.NET Core. Требуется опыт REST API, SQL Server, интеграций и авторизации. Проверка изменений и Docker. Полное описание работодателя.'};return {vacancy:{url,vacancyId:id,provider:'hh',title:f.title,description:f.description,descriptionCoverage:'full-dom'}};}return {ok:true};},update:async(n,o)=>Object.assign(tabs.get(n),o)}}};
context.fetch=async(url,options={})=>{http.push({url,body:options.body||'',method:options.method||'GET'});let value={};
 if(String(url).startsWith('https://api.hh.ru/vacancies/')){const vacancyId=String(url).match(/\/vacancies\/(\d+)/)?.[1]||'';const fixtures={
  '779':{name:'Специалист технической поддержки',description:'<p>Техническая поддержка SaaS-платформы: тикеты, API, SQL, логи и письменные обращения. Телефонные звонки не требуются.</p>'},
  '780':{name:'Менеджер по работе с клиентами в чатах',description:'<p>Общение только в чате, письменная коммуникация, поиск информации и решение вопросов. Без звонков.</p>'},
  '781':{name:'Консультант Информационно-консультационный центр Банка',description:'<p>Принимать входящие звонки клиентов, консультировать по банковским продуктам и фиксировать результаты обращений.</p>'},
  '784':{name:'Специалист технической поддержки / Support L1',description:'<p>Регистрация обращений пользователей и партнеров. Консультирование через чаты, Telegram и Reddit. Работа с тикетами и базой знаний. Телефонные звонки не требуются.</p>'}
 };value={id:vacancyId,...(fixtures[vacancyId]||{name:'Junior .NET Backend Developer',description:'<p>C# ASP.NET Core REST API SQL Server. Коммуникация через задачи и командный чат.</p>'}),employer:{name:'Fixture Employer'},key_skills:[],schedule:{name:'Удаленная работа'}};return {ok:true,status:200,json:async()=>value,text:async()=>JSON.stringify(value)};}
 if(url.endsWith('/chat/completions')){const body=JSON.parse(options.body),payload=JSON.parse(body.messages[1].content);if(JSON.stringify(payload).includes('SLOW_TEST'))await new Promise(r=>setTimeout(r,800));const X=context.vjaContextReply,p=await vm.runInContext('cpData()',context),c=X.build(p.profile,payload.vacancy||{},{messages:payload.recentMessages||[],candidateDraft:''});const facts=payload.candidateFacts||[];const chosen=facts.find(f=>/appxite-api/.test(f.id))||facts[0];const qs=payload.questions||[];value={choices:[{message:{content:JSON.stringify({text:chosen?.text||'Работаю с API и интеграциями.',factIds:chosen?[chosen.id]:[],answeredQuestions:qs.map(q=>q.id),missingFacts:[]})}}]};}if(url.endsWith('/api/operator/recruiter/triage')){const s=JSON.parse(options.body).text;if(s.includes('SLOW_TEST'))await new Promise(r=>setTimeout(r,800));value={suggestedReply:'Спасибо! Буду рада подробнее обсудить задачи.'};}return {ok:true,status:200,json:async()=>value,text:async()=>JSON.stringify(value)};};
vm.createContext(context);context.importScripts=(...files)=>files.forEach(f=>vm.runInContext(fs.readFileSync(path.join(ROOT,f),'utf8'),context,{filename:f}));vm.runInContext(fs.readFileSync(path.join(ROOT,'background.js'),'utf8'),context,{filename:'background.js'});
async function request(message,sender){tabs.set(sender.tab?.id||7,{id:sender.tab?.id||7,url:sender.url,status:'complete'});return new Promise(resolve=>{let handled=false;for(const f of listeners){let sent=false;const v=f(message,sender,result=>{sent=true;handled=true;resolve(clone(result));});if(v===true){handled=true;break;}if(sent)break;}if(!handled)resolve(null);});}
require('node:readline').createInterface({input:process.stdin}).on('line',async line=>{let q;try{q=JSON.parse(line);let result;
 if(q.op==='set'){await vm.runInContext('cpInitialize()',context);Object.assign(data,q.data||{});result=true;}
 else if(q.op==='get')result={data:clone(data),http:clone(http)};
 else if(q.op==='eval')result=await vm.runInContext(q.code,context);
 else result=await request(q.message,q.sender);
 process.stdout.write(JSON.stringify({id:q.id,result})+'\n');
 }catch(e){process.stdout.write(JSON.stringify({id:q?.id,error:e.stack||e.message})+'\n');}});
