/* Organized settings UI over the existing Copilot profile/storage. */
(async function(){
'use strict';
const C=globalThis.vjaCopilotCore,T=globalThis.vjaCandidateTruth;const node=id=>document.getElementById(id);let savedProfile=null;
function field(label,id,value='',type='text'){const l=document.createElement('label');l.textContent=label;const i=document.createElement('input');i.type=type;i.id=id;i.value=value;l.append(i);return l;}
function button(text,fn){const b=document.createElement('button');b.type='button';b.textContent=text;b.addEventListener('click',fn);return b;}
function status(text){node('cpSaveStatus').textContent=text;}
function select(values,value){const s=document.createElement('select');for(const [v,label] of Object.entries(values)){const o=document.createElement('option');o.value=v;o.textContent=label;o.selected=v===value;s.append(o);}return s;}
function addFact(f={}){
 const row=document.createElement('div');row.className='cpFact';row.dataset.id=f.id||C.newId();
 const kind=select({skill:'Навык',experience:'Рабочий опыт',task:'Задачи',project_detail:'Детали проекта',project:'Проект',education:'Образование',language:'Язык',communication:'Общение',teaching:'Обучение',other:'Другое'},f.kind||'skill');kind.className='cpKind';kind.setAttribute('aria-label','Тип факта');
 const state=select({CONFIRMED:'Подтверждено',TRANSFERABLE:'Переносимый навык',INFERENCE:'Предположение',UNKNOWN:'Неизвестно'},f.status||'UNKNOWN');state.className='cpState';state.setAttribute('aria-label','Достоверность');
 const text=document.createElement('textarea');text.value=f.text||'';text.rows=2;text.className='cpText';text.placeholder='Только реальные сведения';text.setAttribute('aria-label','Содержание факта');
 const source=document.createElement('input');source.type='text';source.value=f.source||'';source.className='cpSource';source.placeholder='Источник: CV, диплом, ваш комментарий';source.setAttribute('aria-label','Источник факта');
 const roles=document.createElement('div');roles.className='cpRoles';for(const [id,label] of Object.entries(C.labels)){const l=document.createElement('label');const cb=document.createElement('input');cb.type='checkbox';cb.value=id;cb.checked=(f.roles||[]).includes(id);l.append(cb,document.createTextNode(label));roles.append(l);}
 const details=document.createElement('details');const summary=document.createElement('summary');summary.textContent='Для каких ролей';details.append(summary,roles);
 row.append(kind,state,text,source,details,button('Удалить',()=>row.remove()));node('cpFacts').append(row);
}
function addReply(r={}){
 const row=document.createElement('div');row.className='cpReply';row.dataset.id='default-feedback-ru';
 const name=document.createElement('input');name.value=r.label||r.name||'Спасибо, буду ждать';name.placeholder='Название';name.className='cpReplyName';name.setAttribute('aria-label','Название основного быстрого ответа');
 const text=document.createElement('textarea');text.value=r.text||globalThis.vjaQuickReplies?.defaultPersonalReply?.text||'';text.rows=5;text.placeholder='Здравствуйте! Спасибо за ответ…';text.className='cpReplyText';text.setAttribute('aria-label','Текст основного быстрого ответа');
 row.append(name,text);node('cpReplies').append(row);
}
const profileSection=document.createElement('section');profileSection.className='card';profileSection.id='profileSection';
profileSection.innerHTML=`<h2>Профиль</h2><p>Единый источник подтверждённых данных для CV, сопроводительных писем, форм и recruiter-чата.</p><div id="cpContacts" class="fieldGrid"></div><h3>Подтверждённые факты</h3><details class="group"><summary>Показать / изменить факты</summary><div id="cpFacts"></div><div id="cpAddFact" class="actions"></div></details><div class="actions"><button id="cpSave" class="primary">Сохранить профиль и настройки</button></div><div id="cpSaveStatus" class="status" role="status" aria-live="polite"></div><pre id="cpDebugInfo" hidden></pre>`;
const aiSection=document.createElement('section');aiSection.className='card';aiSection.id='aiSettings';
aiSection.innerHTML=`<h2>AI и ответы</h2><p>✎ AI работает с текущим открытым recruiter-чатом. Видимых быстрых ответов всего пять; основной можно изменить ниже.</p><details class="group" open><summary>Основной быстрый ответ</summary><p class="status">Используется для сообщений вроде «рассмотрим резюме и дадим обратную связь». Переменные: {{email}}, {{telegram}}, {{firstName}}.</p><div id="cpReplies"></div></details><details class="group" open><summary>AI и приватность</summary><label><input id="cpConsent" type="checkbox"> Разрешаю AI анализировать текущую вакансию, профиль и сообщения именно открытого recruiter-чата.</label><p class="status">AI не отправляет сообщение работодателю: он только предлагает или улучшает текст в активном чате.</p><label><input id="cpDiscovery" type="checkbox"> Разрешить фоновый сбор вакансий для автопилота.</label><br><label><input id="cpDebug" type="checkbox"> Режим диагностики</label><div class="row"><label for="cpHistory">Шаги подгрузки истории чата</label><input id="cpHistory" type="number" min="1" max="40" value="24"></div></details><details class="group"><summary>Горячие клавиши</summary><div id="cpCommands" class="status"></div><div id="cpCommandActions" class="actions"></div></details><details class="group"><summary>Разрешённые сайты</summary><p class="status">Новый сайт включается только после вашего разрешения через значок расширения.</p><div id="cpSites"></div></details><div class="actions"><button id="cpSaveAi" class="primary">Сохранить AI и ответы</button></div>`;
const style=document.createElement('style');style.textContent='.cpFact,.cpReply{display:grid;grid-template-columns:1fr 1fr;gap:8px;padding:13px 0;border-top:1px solid #eee}.cpText,.cpSource,.cpReplyText,.cpFact details{grid-column:1/-1}.cpReplyName{grid-column:1/-1}.cpRoles{display:flex;gap:8px;flex-wrap:wrap;padding:8px 0}.cpRoles label{font-size:11px}#profileSection textarea,#profileSection select,#profileSection input[type=number],#aiSettings textarea,#aiSettings select,#aiSettings input[type=number]{padding:9px;border:1px solid #d8d0e4;border-radius:8px;font:inherit;width:100%;background:white}#profileSection h3,#aiSettings h3{font-size:15px;margin-top:20px}#cpSites>div{display:flex;align-items:center;justify-content:space-between;gap:12px;margin:8px 0}#cpDebugInfo{overflow:auto;max-height:200px}';document.head.append(style);
(node('profileMount')||document.querySelector('main')).append(profileSection);(node('aiMount')||document.querySelector('main')).append(aiSection);
await chrome.runtime.sendMessage({type:'vjaCopilot',op:'memory'});
const stored=await chrome.storage.local.get(['vjaCandidateTruthProfile','applicationMemory','vjaCopilotSettings','vjaPersonalReplies']);
savedProfile=C.profile(stored.vjaCandidateTruthProfile);if(stored.applicationMemory?.phone!==undefined)savedProfile.contacts.phone=stored.applicationMemory.phone;
for(const [label,id,value,type] of [['Полное имя','cpName',savedProfile.fullName],['Имя','cpFirstName',savedProfile.firstName],['Фамилия','cpLastName',savedProfile.lastName],['Email','cpEmail',savedProfile.contacts.email,'email'],['Telegram','cpTelegram',savedProfile.contacts.telegram],['Телефон (необязательно)','cpPhone',savedProfile.contacts.phone,'tel'],['Город / местоположение','cpLocation',savedProfile.location],['GitHub','cpGithub',savedProfile.github,'url'],['Портфолио','cpPortfolio',savedProfile.portfolio,'url'],['LinkedIn (необязательно)','cpLinkedin',savedProfile.linkedin,'url']])node('cpContacts').append(field(label,id,value,type));
for(const f of savedProfile.facts)addFact(f);
const russianReplies=(stored.vjaPersonalReplies||[]).filter(r=>!r.language||r.language==='ru');const primaryReply=russianReplies.find(r=>r.id==='default-feedback-ru')||globalThis.vjaQuickReplies?.defaultPersonalReply;addReply(primaryReply||{});
node('cpConsent').checked=Boolean(stored.vjaCopilotSettings?.aiConsent);node('cpDiscovery').checked=Boolean(stored.vjaCopilotSettings?.discoveryEnabled);node('cpDebug').checked=Boolean(stored.vjaCopilotSettings?.debug);node('cpHistory').value=stored.vjaCopilotSettings?.historyLimit||24;if(node('cpQuickListCoverLetter'))node('cpQuickListCoverLetter').checked=stored.vjaCopilotSettings?.quickListCoverLetter!==false;
node('cpAddFact').append(button('Добавить факт',()=>addFact()));
node('cpSave').addEventListener('click',async()=>{
 try{
  const p=C.profile({...savedProfile,fullName:node('cpName').value,firstName:node('cpFirstName').value,lastName:node('cpLastName').value,contacts:{...savedProfile.contacts,email:node('cpEmail').value,telegram:node('cpTelegram').value,phone:node('cpPhone').value},location:node('cpLocation').value,github:node('cpGithub').value,portfolio:node('cpPortfolio').value,linkedin:node('cpLinkedin').value,facts:[...node('cpFacts').children].map(r=>{const prev=savedProfile.facts.find(f=>f.id===r.dataset.id)||{},text=r.querySelector('.cpText').value,changed=prev.text!==text;return {...prev,id:r.dataset.id,text,textRu:changed?text:prev.textRu,textEn:changed?'':prev.textEn,status:r.querySelector('.cpState').value,kind:r.querySelector('.cpKind').value,source:r.querySelector('.cpSource').value,origin:changed?'user-confirmed':prev.origin,priority:changed?100:prev.priority,roles:[...r.querySelectorAll('.cpRoles input:checked')].map(i=>i.value)};}),updatedAt:Date.now()});
  p.deletedFactIds=[...new Set([...(savedProfile.deletedFactIds||[]),...savedProfile.facts.filter(f=>!p.facts.some(n=>n.id===f.id)).map(f=>f.id)])];p.profileRevision=T.revision(p);
  const personalReplies=[...node('cpReplies').children].slice(0,1).map(r=>({id:'default-feedback-ru',label:r.querySelector('.cpReplyName').value.trim().slice(0,60)||'Спасибо, буду ждать',language:'ru',text:r.querySelector('.cpReplyText').value.trim().slice(0,2500)})).filter(r=>r.text);
  const previous=(await chrome.storage.local.get(['applicationMemory','vjaCopilotSettings'])),mem=previous.applicationMemory||{},oldSettings=previous.vjaCopilotSettings||{};const settings={...oldSettings,aiConsent:node('cpConsent').checked,discoveryEnabled:node('cpDiscovery').checked,debug:node('cpDebug').checked,historyLimit:Math.min(40,Math.max(1,Number(node('cpHistory').value)||24)),floatingApplyMode:'auto',alwaysCoverLetter:true,compactApplyStatus:true,quickListCoverLetter:node('cpQuickListCoverLetter')?node('cpQuickListCoverLetter').checked:true};
  await chrome.storage.local.set({vjaCandidateTruthProfile:p,applicationMemory:{...mem,phone:p.contacts.phone},vjaPersonalReplies:personalReplies,vjaCopilotSettings:settings});savedProfile=p;status('Сохранено. Открытые чаты обновятся автоматически или после обновления страницы.');
  node('cpDebugInfo').hidden=!settings.debug;node('cpDebugInfo').textContent=JSON.stringify({version:C.VERSION,facts:p.facts.length,confirmed:C.confirmed(p).length,settings},null,2);
 }catch(e){status('Не удалось сохранить: '+e.message);}
});
node('cpSaveAi')?.addEventListener('click',()=>node('cpSave').click());
const commands=await chrome.commands.getAll();node('cpCommands').textContent=commands.filter(c=>c.name!=='_execute_action').map(c=>`${c.description}: ${c.shortcut||'не назначено'}`).join(' · ');node('cpCommandActions').append(button('Изменить сочетания клавиш',()=>chrome.tabs.create({url:'chrome://extensions/shortcuts'})));
async function showSites(){node('cpSites').replaceChildren();for(const s of await chrome.scripting.getRegisteredContentScripts()){if(!s.id.startsWith('vja-site-'))continue;const row=document.createElement('div'),label=document.createElement('span');label.textContent=s.matches.join(', ');row.append(label,button('Отозвать',async()=>{await chrome.permissions.remove({origins:s.matches});await chrome.scripting.unregisterContentScripts({ids:[s.id]}).catch(()=>{});await showSites();}));node('cpSites').append(row);}}await showSites();
})().catch(e=>{const n=document.getElementById('cpSaveStatus');if(n)n.textContent='Настройки не загрузились: '+e.message;});
