/* Local real-label logistic-regression trainer. Never fabricates labels. */
(function(root,factory){const api=factory(root);if(typeof module==='object'&&module.exports)module.exports=api;if(root)root.vjaBrowserTrainer=api;})(globalThis,function(root){
 'use strict';
 const R=root.vjaModelRuntime||((typeof require==='function')?require('./model-runtime.js'):null);
 const sigmoid=z=>R.sigmoid(z),clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
 function metrics(rows,probs,threshold=.5){let tp=0,fp=0,tn=0,fn=0,brier=0;for(let i=0;i<rows.length;i++){const y=Number(rows[i].labelUserApply),p=probs[i],z=p>=threshold?1:0;brier+=(p-y)**2;if(z&&y)tp++;else if(z&&!y)fp++;else if(!z&&y)fn++;else tn++;}const precision=tp/(tp+fp||1),recall=tp/(tp+fn||1),f1=2*precision*recall/(precision+recall||1),accuracy=(tp+tn)/(rows.length||1);return {n:rows.length,accuracy,precision,recall,f1,brier:brier/(rows.length||1),threshold};}
 function split(rows){const x=[...rows].filter(r=>[0,1].includes(r.labelUserApply)).sort((a,b)=>Number(a.timestamp)-Number(b.timestamp));if(x.length<40)throw new Error('Нужно минимум 40 реальных Apply/Save/Skip/Fit labels для локального обучения.');const positives=x.filter(r=>r.labelUserApply===1).length,negatives=x.length-positives;if(Math.min(positives,negatives)<10)throw new Error('Нужно минимум 10 положительных и 10 отрицательных real labels.');let a=Math.max(20,Math.floor(x.length*.7)),b=Math.max(a+8,Math.floor(x.length*.85));b=Math.min(b,x.length-8);return {train:x.slice(0,a),cal:x.slice(a,b),test:x.slice(b)};}
 async function vectors(rows,dim){return Promise.all(rows.map(r=>R.vector(r,dim)));}
 async function trainPreference(rows,{dimension=256,epochs=160,learningRate=.22,l2=.002}={}){const s=split(rows),X=await vectors(s.train,dimension),w=Array(dimension).fill(0);for(let e=0;e<epochs;e++){const g=Array(dimension).fill(0);for(let i=0;i<X.length;i++){const p=sigmoid(w.reduce((z,a,j)=>z+a*X[i][j],0)),err=p-s.train[i].labelUserApply;for(let j=0;j<dimension;j++)if(X[i][j])g[j]+=err*X[i][j];}const rate=learningRate/(1+e*.01);for(let j=0;j<dimension;j++)w[j]-=rate*(g[j]/X.length+l2*w[j]);}
 const predictRows=async rs=>{const vx=await vectors(rs,dimension);return vx.map(x=>sigmoid(w.reduce((z,a,j)=>z+a*x[j],0)));};const cp=await predictRows(s.cal);let best={f1:-1,threshold:.5};for(let t=.30;t<=.70;t+=.025){const m=metrics(s.cal,cp,t);if(m.f1>best.f1)best=m;}const tp=await predictRows(s.test),testMetrics=metrics(s.test,tp,best.threshold),now=new Date().toISOString();return {schemaVersion:1,modelType:'personal-vacancy-logreg',modelVersion:'local-pref-'+Date.now(),dimension,weights:w,threshold:Number(best.threshold.toFixed(3)),calibration:{type:'none'},trainedOnRealLabels:true,trainingLabels:s.train.length,validation:{...best,split:'chronological-calibration'},testMetrics:{...testMetrics,split:'chronological-held-out'},training:{source:'extension-local-real-labels',epochs,learningRate,l2,createdAt:now,totalLabels:rows.length,train:s.train.length,calibration:s.cal.length,test:s.test.length}};}
 return {metrics,split,trainPreference};
});
