(function(root){
  'use strict';
  const css=`:host{all:initial;color-scheme:light}*{box-sizing:border-box}button,input,textarea,select{font:inherit}button{cursor:pointer}button:disabled{opacity:.5;cursor:default}button:focus-visible,textarea:focus-visible,select:focus-visible{outline:3px solid #a898ff;outline-offset:2px}.bar{display:flex;gap:5px;align-items:center;padding:4px;border:1px solid #e3dff1;border-radius:14px;background:#fffffff5;box-shadow:0 3px 14px #241b4f12;font:12px/1.45 system-ui,sans-serif}.bar button{border:0;border-radius:10px;padding:8px 11px;color:#463777;background:transparent;white-space:nowrap}.bar button:hover{background:#f1edfb}.bar .main{background:#6554bd;color:white}.card{width:min(390px,calc(100vw - 24px));max-height:72vh;overflow:auto;border:1px solid #e1dced;border-radius:16px;background:#fff;box-shadow:0 14px 54px #24203924;font:13px/1.55 system-ui,sans-serif;color:#292537}.head{display:flex;gap:12px;align-items:center;padding:13px 15px;background:#faf8fe;border-bottom:1px solid #efebf6}.head strong{flex:1;font-size:14px}.head button{border:0;border-radius:8px;background:none;color:#625870;font-size:20px}.body{padding:14px}.status{font-size:12px;color:#62596f;margin:8px 0;white-space:pre-line}.hint{font-size:11px;color:#7c7189;margin:8px 0}.draft{display:block;width:100%;min-height:125px;resize:vertical;border:1px solid #dcd6e7;border-radius:10px;padding:11px;color:#292537;background:white;font:13px/1.55 system-ui}.actions{display:flex;gap:6px;flex-wrap:wrap;margin-top:10px}.actions button,.choice{border:1px solid #e0dae9;background:#fff;color:#544673;border-radius:9px;padding:7px 10px;font-size:12px}.actions .primary{background:#6554bd;border-color:#6554bd;color:#fff}.choice{display:block;width:100%;text-align:left;margin-top:7px}.choice small{display:block;color:#81748b}.summary{font-size:12px;color:#514765;padding:9px 10px;background:#f8f6fc;border-radius:10px;white-space:pre-line}.toast{max-width:min(330px,calc(100vw - 24px));padding:9px 12px;border:1px solid #e2ddec;border-radius:12px;background:#fffffff8;box-shadow:0 8px 28px #251d4b1c;color:#55486f;font:12px/1.45 system-ui,sans-serif;white-space:pre-line}.toast.ok{border-color:#cce7d5;color:#17633a}.toast.warn{border-color:#eed9ad;color:#855715}.toast.bad{border-color:#efc9c5;color:#9f2e28}.hidden{display:none!important}@media(prefers-reduced-motion:no-preference){button{transition:background .12s ease}}`;
  function host(kind){const h=document.createElement('div');h.dataset.vjaRoot=kind;h.style.cssText='position:fixed;z-index:2147483646;max-width:calc(100vw - 16px)';const shadow=h.attachShadow({mode:'open'}),style=document.createElement('style');style.textContent=css;shadow.append(style);document.documentElement.append(h);return {host:h,root:shadow};}
  function button(label,fn,cls=''){const b=document.createElement('button');b.type='button';b.textContent=label;b.className=cls;b.addEventListener('click',fn);return b;}
  function place(h,anchor,above=true){if(!h?.isConnected)return;const rect=anchor?.getBoundingClientRect?.();const width=h.getBoundingClientRect().width,height=h.getBoundingClientRect().height;h.style.left=Math.max(8,Math.min(innerWidth-width-8,rect?rect.right-width:innerWidth-width-18))+'px';h.style.top=Math.max(8,Math.min(innerHeight-height-8,rect?(above?rect.top-height-8:rect.bottom+8):innerHeight-height-20))+'px';}
  function bar(items,anchor=null){const x=host('bar'),box=document.createElement('div');box.className='bar';box.setAttribute('role','toolbar');box.setAttribute('aria-label','Violetta Apply Assistant');for(const item of items)box.append(button(item.label,item.onClick,item.primary?'main':''));x.root.append(box);place(x.host,anchor);return {...x,box,place:()=>place(x.host,anchor),remove:()=>x.host.remove()};}
  function toast(text,anchor=null,kind='neutral',timeout=0){const x=host('toast'),box=document.createElement('div');box.className='toast'+(kind&&kind!=='neutral'?' '+kind:'');box.setAttribute('role','status');box.setAttribute('aria-live','polite');box.textContent=text;x.root.append(box);place(x.host,anchor);let timer=timeout?setTimeout(()=>x.host.remove(),timeout):null;return {...x,box,setText(value,nextKind=kind){box.textContent=value;box.className='toast'+(nextKind&&nextKind!=='neutral'?' '+nextKind:'');place(x.host,anchor);},place:()=>place(x.host,anchor),close:()=>{if(timer)clearTimeout(timer);x.host.remove();}};}
  function panel(title,anchor=null,onClose=()=>{}){const x=host('panel'),section=document.createElement('section');section.className='card';section.setAttribute('role','dialog');section.setAttribute('aria-label',title);const head=document.createElement('div');head.className='head';const strong=document.createElement('strong');strong.textContent=title;const close=()=>{x.host.remove();onClose();};const cb=button('×',close);cb.setAttribute('aria-label','Закрыть');head.append(strong,cb);const body=document.createElement('div');body.className='body';section.append(head,body);x.root.append(section);x.host.addEventListener('keydown',e=>{if(e.key==='Escape'){e.stopPropagation();close();}});place(x.host,anchor);return {...x,body,close,place:()=>place(x.host,anchor),status(text){const p=document.createElement('p');p.className='status';p.setAttribute('role','status');p.setAttribute('aria-live','polite');p.textContent=text;body.append(p);return p;}};}
  root.vjaCopilotUI={button,bar,panel,toast,place};
})(globalThis);
