'use strict';
const q=id=>document.getElementById(id);const request=(op,args={})=>chrome.runtime.sendMessage({type:'vjaCopilot',op,...args});
function download(name,data,type='application/json'){const blob=new Blob([data],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),500);}
function pills(obj={}){return Object.entries(obj).filter(([,v])=>Math.abs(Number(v))>=.5).sort((a,b)=>Math.abs(b[1])-Math.abs(a[1])).slice(0,16).map(([k,v])=>`<span class="pill ${v>0?'pos':'neg'}">${k}: ${v>0?'+':''}${Math.round(v*10)/10}</span>`).join('');}
async function refresh(){q('status').textContent='Обновляю…';const [s,a]=await Promise.all([request('learning-summary'),request('applications')]);if(!s?.ok){q('status').textContent=s?.error||'Learning summary недоступен';return;}q('events').textContent=s.events;q('labels').textContent=s.labels;q('signals').textContent=`${Math.round(s.signals?.positive||0)} / ${Math.round(s.signals?.negative||0)}`;q('ready').textContent=s.trainingReady?'Можно обучать baseline':'Собираем labels';const weights=[pills(s.signals?.roleWeights),pills(s.signals?.techWeights)].filter(Boolean).join('');q('weights').innerHTML=weights||'<span class="pill">Пока недостаточно решений. Используйте Apply / Save / Skip и ✓ / ✕ возле Fit.</span>';const o=a?.outcomeAnalytics||{};q('outcomes').innerHTML=`<span class="metric">Отклики <strong>${o.applied||0}</strong></span><span class="metric">Ответы <strong>${o.reply||0}</strong></span><span class="metric">Интервью <strong>${o.interview||0}</strong></span><span class="metric">Офферы <strong>${o.offer||0}</strong></span><br>Reply rate: ${o.replyRate||0}% · Interview rate: ${o.interviewRate||0}% · n=${o.sampleSize||0}${o.lowSample?' · малая выборка':''}`;const r=s.registry||{};q('registry').textContent=r.activeModel?`Active: ${r.activeModel} · models: ${(r.models||[]).length}`:`Active ML model: нет. Персональные signals работают без fake ML. Models in registry: ${(r.models||[]).length}`;q('status').textContent=`Learning schema v${s.schemaVersion}. Для устойчивой персональной модели рекомендовано ≥ ${s.minimumRecommendedLabels} labels.`;}
q('refresh').addEventListener('click',()=>void refresh());
q('export').addEventListener('click',async()=>{const r=await request('learning-export');if(r?.ok)download(`violetta-learning-backup-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify(r.data,null,2));});
q('dataset').addEventListener('click',async()=>{const r=await request('learning-export');if(r?.ok)download(`violetta-preference-dataset-${new Date().toISOString().slice(0,10)}.jsonl`,(r.data.dataset||[]).map(x=>JSON.stringify(x)).join('\n')+'\n','application/x-ndjson');});
q('importFile').addEventListener('change',async e=>{const f=e.target.files?.[0];if(!f)return;try{const data=JSON.parse(await f.text()),r=await request('learning-import',{data});q('status').textContent=r?.ok?`Импортировано. Events: ${r.events}`:(r?.error||'Ошибка импорта');await refresh();}catch(err){q('status').textContent='Некорректный JSON: '+err.message;}e.target.value='';});
q('reset').addEventListener('click',async()=>{if(!confirm('Удалить только learning events и model registry? История откликов и CV не удаляются.'))return;const r=await request('learning-reset');q('status').textContent=r?.ok?'Learning data сброшены.':r?.error||'Ошибка';await refresh();});
void refresh();
