const test=require('node:test');const assert=require('node:assert/strict');const L=require('./learning-core.js');
test('learning event validates supported types',()=>{const e=L.event({type:'VACANCY_APPLIED',vacancy:{vacancyId:'1',title:'Support'}});assert.equal(e.type,'VACANCY_APPLIED');assert.equal(e.vacancyId,'1');assert.throws(()=>L.event({type:'NOPE'}));});
test('positive and negative vacancy decisions become preference signals',()=>{const events=[L.event({type:'VACANCY_APPLIED',meta:{features:{role:'technical_support',technologies:['c#'],remote:true,calls:'no-calls'}}}),L.event({type:'VACANCY_SKIPPED',meta:{features:{role:'sales',technologies:['1c'],sales:true,calls:'calls'}}})];const s=L.deriveSignals(events);assert.ok(s.roleWeights.technical_support>0);assert.ok(s.roleWeights.sales<0);assert.ok(s.techWeights['c#']>0);});
test('learning adjustment is bounded and explainable',()=>{const s={total:50,roleWeights:{technical_support:8},techWeights:{'c#':8},companyWeights:{},remoteWeight:8,callsWeight:0,salesWeight:0};const out=L.adjustFit({score:80,features:{role:'technical_support',technologies:['c#'],remote:true,calls:'no-calls'},preferences:{minimumFitScore:80}},s,{company:'X'});assert.ok(out.score>=80&&out.score<=95);assert.equal(out.algorithm,'rules-v1+personal-signals');assert.ok(out.learning.reasons.length);});
test('active learning bands confidence',()=>{assert.equal(L.confidenceBand(.95),'AUTO');assert.equal(L.confidenceBand(.8),'REVIEW');assert.equal(L.confidenceBand(.4),'ASK');});
test('question similarity recognizes paraphrase overlap',()=>{assert.ok(L.semanticSimilarity('Какой уровень английского языка?','Укажите уровень английского')>.3);});
test('dataset export only labels apply-like decisions',()=>{const rows=L.datasetRows([L.event({type:'VACANCY_APPLIED',vacancy:{vacancyId:'1'},meta:{features:{role:'developer'}}}),L.event({type:'VACANCY_SKIPPED',vacancy:{vacancyId:'2'},meta:{features:{role:'sales'}}}),L.event({type:'OUTCOME_CHANGED'})]);assert.equal(rows.length,2);assert.deepEqual(rows.map(x=>x.labelUserApply),[1,0]);});
test('preference dataset collapses repeated labels for the same vacancy to the latest decision',()=>{const rows=L.datasetRows([L.event({type:'VACANCY_SAVED',timestamp:1,vacancy:{vacancyId:'1'},meta:{features:{role:'developer'}}}),L.event({type:'VACANCY_SKIPPED',timestamp:2,vacancy:{vacancyId:'1'},meta:{features:{role:'developer'}}})]);assert.equal(rows.length,1);assert.equal(rows[0].labelUserApply,0);assert.equal(rows[0].sourceEventType,'VACANCY_SKIPPED');});
test('engagement dataset keeps preference and employer response targets separate',()=>{const rows=L.engagementDatasetRows([L.event({type:'OUTCOME_CHANGED',timestamp:1,vacancy:{vacancyId:'1'},userAction:'Applied',meta:{status:'Applied',features:{role:'developer'}}}),L.event({type:'OUTCOME_CHANGED',timestamp:2,vacancy:{vacancyId:'1'},userAction:'Recruiter Replied',meta:{status:'Recruiter Replied',features:{role:'developer'}}}),L.event({type:'OUTCOME_CHANGED',timestamp:3,vacancy:{vacancyId:'2'},userAction:'Rejected',meta:{status:'Rejected',features:{role:'support'}}})]);assert.deepEqual(rows.map(x=>x.labelEmployerEngagement).sort(),[0,1]);});
