'use strict';
const q=id=>document.getElementById(id);const request=(op,args={})=>chrome.runtime.sendMessage({type:'vjaCopilot',op,...args});
function download(name,data,type='application/json'){const blob=new Blob([data],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),500);}
function pills(obj={}){return Object.entries(obj).filter(([,v])=>Math.abs(Number(v))>=.5).sort((a,b)=>Math.abs(b[1])-Math.abs(a[1])).slice(0,16).map(([k,v])=>`<span class="pill ${v>0?'pos':'neg'}">${escapeHtml(k)}: ${v>0?'+':''}${Math.round(v*10)/10}</span>`).join('');}
function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function pct(v){return Number.isFinite(Number(v))?`${Math.round(Number(v)*1000)/10}%`:'—';}
let latestSummary=null;
function renderRegistry(reg={}){const models=Array.isArray(reg.models)?reg.models:[],activePref=reg.activeModels?.preference||reg.activeModel||null,activeEng=reg.activeModels?.engagement||null;q('registry').innerHTML=`<div><strong>Preference active:</strong> ${escapeHtml(activePref||'нет')}</div><div><strong>Engagement active:</strong> ${escapeHtml(activeEng||'нет')}</div><div><strong>Models:</strong> ${models.length}</div>`;const sel=q('modelSelect');sel.replaceChildren(new Option('—',''));for(const m of models.filter(x=>x.status!=='active')){const o=new Option(`${m.modelVersion} · ${m.modelType} · n=${m.trainingLabels||0} · F1=${Number(m.validation?.f1||0).toFixed(3)}`,m.modelVersion);sel.add(o);}q('promote').disabled=!sel.value;}
function renderMonitor(m,monitorId='monitor',retrainId='retrain',empty='Active model: нет.'){const box=q(monitorId),call=q(retrainId);if(!m||!m.modelVersion){box.textContent=empty;call.textContent='';call.className='callout';return;}const x=m.metrics||{},d=m.drift||{};box.innerHTML=`<strong>${escapeHtml(m.modelVersion)}</strong> · labelled predictions ${m.labelledPredictions||0}<br>Accuracy ${pct(x.accuracy)} · F1 ${Number(x.f1||0).toFixed(3)} · Brier ${Number(x.brier||0).toFixed(3)} · ECE ${Number(x.ece||0).toFixed(3)}${d.available?`<br>Prediction shift ${Number(d.meanPredictionShift||0).toFixed(3)} · label-rate shift ${Number(d.positiveRateShift||0).toFixed(3)}`:''}`;const r=m.retraining||{};call.textContent=r.recommended?`Рекомендуется переобучение: ${(r.reasons||[]).join(' · ')}`:`Retraining пока не требуется. Новых labels после обучения: ${r.labelsSinceTraining||0}.`;call.className='callout '+(r.recommended?'warn':'ok');}
async function refresh(){q('status').textContent='Обновляю…';const [s,a]=await Promise.all([request('learning-summary'),request('applications')]);if(!s?.ok){q('status').textContent=s?.error||'Learning summary недоступен';return;}latestSummary=s;q('events').textContent=s.events;q('labels').textContent=s.labels;q('engagementLabels').textContent=s.engagementLabels||0;q('ready').textContent=s.trainingReady?'Preference: production-ready':(s.experimentalTrainingReady?'Preference: experimental only':'Собираем labels');const weights=[pills(s.signals?.roleWeights),pills(s.signals?.techWeights)].filter(Boolean).join('');q('weights').innerHTML=weights||'<span class="pill">Пока недостаточно решений. Используйте Apply / Save / Skip и ✓ / ✕ возле Fit.</span>';const o=a?.outcomeAnalytics||{};q('outcomes').innerHTML=`<span class="metric">Отклики <strong>${o.applied||0}</strong></span><span class="metric">Ответы <strong>${o.reply||0}</strong></span><span class="metric">Интервью <strong>${o.interview||0}</strong></span><span class="metric">Офферы <strong>${o.offer||0}</strong></span><br>Reply rate: ${o.replyRate||0}% · Interview rate: ${o.interviewRate||0}% · n=${o.sampleSize||0}${o.lowSample?' · малая выборка':''}`;renderRegistry(s.registry||{});renderMonitor(s.monitor,'monitor','retrain','Active preference model: нет. Rules + personal signals остаются основным runtime.');renderMonitor(s.engagementMonitor,'engagementMonitor','engagementRetrain','Active engagement model: нет.');q('status').textContent=`Learning schema v${s.schemaVersion}. Для устойчивой preference-модели рекомендовано ≥ ${s.minimumRecommendedLabels} real labels.`;}
q('refresh').addEventListener('click',()=>void refresh());
q('trainLocal').addEventListener('click',async()=>{q('trainStatus').textContent='Готовлю real-label dataset…';try{const r=await request('learning-export');if(!r?.ok)throw new Error(r?.error||'Dataset недоступен');const model=await globalThis.vjaBrowserTrainer.trainPreference(r.data.dataset||[]);const imp=await request('learning-model-import',{model});if(!imp?.ok)throw new Error(imp?.error||'Не удалось импортировать candidate model');q('trainStatus').textContent=`Candidate ${model.modelVersion} обучен на real labels. Held-out n=${model.testMetrics.n}, F1=${model.testMetrics.f1.toFixed(3)}. Проверьте Model Registry перед Promote.`;await refresh();}catch(err){q('trainStatus').textContent=err.message||String(err);}});
q('export').addEventListener('click',async()=>{const r=await request('learning-export');if(r?.ok)download(`violetta-learning-backup-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify(r.data,null,2));});
q('dataset').addEventListener('click',async()=>{const r=await request('learning-export');if(r?.ok)download(`violetta-preference-dataset-${new Date().toISOString().slice(0,10)}.jsonl`,(r.data.dataset||[]).map(x=>JSON.stringify(x)).join('\n')+'\n','application/x-ndjson');});
q('engagementDataset').addEventListener('click',async()=>{const r=await request('learning-export');if(r?.ok)download(`violetta-engagement-dataset-${new Date().toISOString().slice(0,10)}.jsonl`,(r.data.engagementDataset||[]).map(x=>JSON.stringify(x)).join('\n')+'\n','application/x-ndjson');});
q('importFile').addEventListener('change',async e=>{const f=e.target.files?.[0];if(!f)return;try{const data=JSON.parse(await f.text()),r=await request('learning-import',{data});q('status').textContent=r?.ok?`Импортировано. Events: ${r.events}`:(r?.error||'Ошибка импорта');await refresh();}catch(err){q('status').textContent='Некорректный JSON: '+err.message;}e.target.value='';});
q('modelFile').addEventListener('change',async e=>{const f=e.target.files?.[0];if(!f)return;try{const model=JSON.parse(await f.text()),r=await request('learning-model-import',{model});q('status').textContent=r?.ok?`Model candidate импортирован: ${r.entry.modelVersion}`:(r?.error||'Ошибка model import');await refresh();}catch(err){q('status').textContent='Некорректная model JSON: '+err.message;}e.target.value='';});
q('modelSelect').addEventListener('change',()=>{q('promote').disabled=!q('modelSelect').value;});
q('promote').addEventListener('click',async()=>{const version=q('modelSelect').value;if(!version)return;if(!confirm(`Promote ${version}? Runtime Fit начнёт использовать этот валидированный model signal вместе с rules.`))return;const r=await request('learning-model-promote',{version});q('status').textContent=r?.ok?`Promoted: ${version}`:(r?.error||'Promotion rejected');await refresh();});
q('disableModel').addEventListener('click',async()=>{if(!confirm('Отключить активный preference ML? Rules + personal signals продолжат работать.'))return;const r=await request('learning-model-disable',{kind:'preference'});q('status').textContent=r?.ok?'Preference ML отключён.':r?.error||'Ошибка';await refresh();});
q('reset').addEventListener('click',async()=>{if(!confirm('Удалить только learning events и model registry? История откликов и CV не удаляются.'))return;const r=await request('learning-reset');q('status').textContent=r?.ok?'Learning data сброшены.':r?.error||'Ошибка';await refresh();});
void refresh();
