/* Additional product surfaces. Existing analysis, writing and application modules are reused. */
'use strict';
let osDiscoverOffset=0,osDiscoverToken=0,osPrivate=null,osPrivateHash='',osAppToken=0;
async function osRequest(op,args={}){const r=await chrome.runtime.sendMessage({type:'vjaOS',op,...args});if(!r?.ok)throw Error(r?.error||'Операция недоступна.');return r;}
function osApps(){return (summary.jobs||[]).map(globalThis.vjaStrategyAnalytics.normalize);}
function osAnalytics(){const dimension=el('analyticsDimension').value,rows=vjaStrategyAnalytics.group(osApps(),dimension);el('analyticsTable').innerHTML=rows.length?'<div class="card table-wrap"><table><caption>Накопленные результаты · '+esc(dimension)+'</caption><thead><tr><th scope="col">Группа</th><th scope="col">Отклики n</th><th scope="col">Просмотры</th><th scope="col">Реакции</th><th scope="col">Интервью</th><th scope="col">Офферы</th><th scope="col">Доля реакций · 95% интервал</th></tr></thead><tbody>'+rows.map(r=>`<tr><th scope="row">${esc(r.key)}${r.lowSample?' · мало данных':''}</th><td>${r.applied}</td><td>${r.viewed}</td><td>${r.engaged}</td><td>${r.interviews}</td><td>${r.offers}</td><td>${pct(r.engagementRate)} · ${r.interval95.map(pct).join('–')}</td></tr>`).join('')+'</tbody></table></div>':'<p>Нет подтверждённых откликов для сравнения. Подготовленный черновик не считается отправленным откликом.</p>';}
function osVacancyCard(r,actions=false){const v=r.vacancy||{},url=safeUrl(v.url),id=String(v.vacancyId||'');return card(v.title||'Вакансия',`<p>${esc(v.company||'')}</p><span class="pill">Fit ${Math.round(r.fit?.score||0)} / 100</span><span class="pill">Звонки: ${esc({'no-calls':'не найдены в описании',calls:'есть',unknown:'не определено'}[r.analysis?.status]||'не определено')}</span><details><summary>Объяснить Fit</summary><p>${(r.fit?.reasons||[]).map(x=>esc(typeof x==='string'?x:x.text||x.reason||JSON.stringify(x))).join('<br>')||'Причины не записаны.'}</p><p>Риски: ${(r.fit?.risks||[]).map(x=>esc(typeof x==='string'?x:JSON.stringify(x))).join('; ')||'не записаны'}</p></details><div class="actions">${url?`<a href="${esc(url)}" target="_blank" rel="noopener">Открыть и проверить отклик ↗</a>`:''}${actions?`<button data-os-decision="SAVED" data-id="${esc(id)}">Сохранить</button><button data-os-decision="SKIPPED" data-id="${esc(id)}">Пропустить</button>`:''}</div>`);}
function osQueue(){const limit=Number(el('queueLimit').value),ready=(summary.ready||[]).filter(r=>storage['vjaVacancyDecision:'+r.vacancy?.vacancyId]?.decision!=='SKIPPED').sort((a,b)=>(b.fit?.score||0)-(a.fit?.score||0));el('queueList').innerHTML=ready.slice(0,limit||100).map(r=>osVacancyCard(r,true)).join('')||'<p>Подходящих вакансий в очереди пока нет.</p>';}
async function osDiscover(){const token=++osDiscoverToken;try{const r=await osRequest('os-index-query',{query:{collection:'vacancies',offset:osDiscoverOffset,limit:25,search:el('discoverSearch').value}});if(token!==osDiscoverToken)return;el('discoverList').innerHTML=r.rows.map(x=>osVacancyCard(x.payload)).join('')||'<p>Вакансии не найдены.</p>';el('discoverPrev').disabled=osDiscoverOffset===0;el('discoverNext').disabled=!r.hasMore;el('discoverPage').textContent=`Страница ${1+osDiscoverOffset/25} · IndexedDB`;}catch(e){if(token!==osDiscoverToken)return;el('discoverList').textContent='Индекс недоступен. Исходные данные не удалены. Откройте диагностику или перестройте индекс.';el('discoverPage').textContent=e.message;}}
const oldRenderApps=renderApps;
renderApps=async function(){const token=++osAppToken;try{const r=await osRequest('os-index-query',{query:{collection:'applications',offset:pageNo*25,limit:25,search:el('appSearch').value}});if(token!==osAppToken)return;if(!Array.isArray(r.rows))throw Error('No indexed result');applications=r.rows.map(x=>{const c=x.payload.context||{};return {...c,id:x.payload.plan?.id||c.id,vacancy:c.vacancy||{},updatedAt:c.updatedAt||x.updatedAt};});el('pageInfo').textContent=`Страница ${pageNo+1} · по 25 записей`;el('prevPage').disabled=pageNo===0;el('nextPage').disabled=!r.hasMore;el('appList').innerHTML=applications.map(a=>card(a.vacancy?.title||'Отклик',`<p>${esc(a.vacancy?.company||'')}</p><span class="pill">${esc(a.status||'Не записан')}</span><p class="muted">${esc(fmt(a.updatedAt))}</p><button data-timeline="${esc(a.id)}">Журнал</button>`)).join('')||'<p>Сохранённых откликов нет.</p>';}catch{if(token===osAppToken)oldRenderApps();}};
function osMessages(){const apps=osApps(),due=vjaFollowUpIntelligence.dueItems(apps);el('followupList').innerHTML=due.slice(0,30).map(a=>card(a.vacancy?.title||'Отклик',`<p>Рекомендован follow-up: ${esc(fmt(a.nextAction.dueAt))}.</p><label>Черновик — проверьте перед отправкой<textarea class="os-draft" readonly>Здравствуйте! Подскажите, пожалуйста, есть ли новости по моему отклику? Буду благодарна за обратную связь.</textarea></label>`)).join('')||'<p>Нет просроченных сохранённых договорённостей. Отсутствие ответа не трактуется как отказ.</p>';const conversations=Object.entries(storage).filter(([k])=>k.startsWith('vjaConversation:'));el('conversationList').textContent=`Сохранённых диалогов: ${conversations.length}. Контекстные ответы создаются в открытой переписке на сайте.`;}
function osInterviews(){el('interviewList').innerHTML=osApps().filter(a=>a.id).slice(0,50).map(a=>card(a.vacancy?.title||'Вакансия',`<p>${esc(a.vacancy?.company||'')}</p><a href="interview.html?id=${encodeURIComponent(a.id)}" target="_blank" rel="noopener">Вопросы и тренировочное интервью →</a>`)).join('')||'<p>Сначала подготовьте отклик на конкретную вакансию.</p>';}
function osSettings(){const p=vjaAutomationPolicy.normalize(storage.vjaAutomationPolicyV1||{});el('automationMode').value=p.mode;el('autopilotConsent').checked=p.explicitOptIn;el('automationPaused').checked=p.paused;el('dailyLimit').value=String(p.dailyLimit);for(const o of el('approvedCategories').options)o.selected=p.approvedCategories.includes(o.value);el('queueLimit').value=String(p.dailyLimit);el('automationSummary').textContent=`${p.mode.toUpperCase()}${p.paused?' · приостановлен':''}`;}
function osOnboarding(){const p=storage.vjaCandidateTruthProfile||{},pref=storage.vjaJobPreferencesV1||{};const steps=[['CV',!!(storage.cvVaultEn?.base64||storage.cvVaultRu?.base64)],['Подтверждённые факты',(p.facts||[]).some(f=>f.status==='CONFIRMED')],['Предпочтения вакансий',Object.keys(pref).length>0],['Отношение к звонкам',Object.hasOwn(pref,'avoidCalls')],['Удалённо / офис',Object.hasOwn(pref,'officeAllowed')],['График',!!(p.schedule||pref.schedule)],['Зарплатные ожидания',!!(p.salary||pref.salary)],['Языки',(p.facts||[]).some(f=>f.kind==='language'&&f.status==='CONFIRMED')],['Контакты',!!(p.contacts?.email||p.contacts?.telegram||p.contacts?.phone)],['Режим работы',!!storage.vjaAutomationPolicyV1]];el('onboarding').innerHTML='<div class="card">'+steps.map(([label,done],i)=>`<div class="step"><strong>${i+1}</strong><span>${esc(label)}</span><span class="pill ${done?'ok':'warn'}">${done?'Настроено':'Настроить или пропустить'}</span></div>`).join('')+'<p class="muted">Пропущенные сведения остаются неизвестными: агент не дополняет их автоматически.</p><a href="options.html">Изменить подтверждённые данные →</a></div>';}
async function osDiagnostics(){try{const r=await osRequest('os-diagnostics');if(r.diagnostics)el('diagnosticText').textContent=JSON.stringify(r.diagnostics,null,2);}catch{/* Existing redacted diagnostics remain visible. */}}
globalThis.vjaOSRefresh=async()=>{osSettings();osQueue();osAnalytics();osMessages();osInterviews();osOnboarding();await osDiagnostics();};
globalThis.vjaOSShowPage=id=>{if(id==='discover')void osDiscover();if(id==='analytics')osAnalytics();if(id==='applications')void renderApps();};
for(const [id,fn] of [['saveAutomation',async()=>{const policy={mode:el('automationMode').value,explicitOptIn:el('autopilotConsent').checked,paused:el('automationPaused').checked,approvedCategories:[...el('approvedCategories').selectedOptions].map(o=>o.value),dailyLimit:Number(el('dailyLimit').value)};await osRequest('os-policy-save',{policy});await refresh();status('Режим сохранён.');}],['rebuildIndex',async()=>{await osRequest('os-index-rebuild');status('Индекс восстановлен из сохранённых данных.');}],['diagnosticCopy',async()=>{await navigator.clipboard.writeText(el('diagnosticText').textContent);status('Диагностика скопирована.');}]])action(id,fn);
el('analyticsDimension').addEventListener('change',osAnalytics);el('queueLimit').addEventListener('change',osQueue);let searchTimer;el('discoverSearch').addEventListener('input',()=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>{osDiscoverOffset=0;void osDiscover();},220);});el('discoverPrev').addEventListener('click',()=>{osDiscoverOffset=Math.max(0,osDiscoverOffset-25);void osDiscover();});el('discoverNext').addEventListener('click',()=>{osDiscoverOffset+=25;void osDiscover();});
el('queueList').addEventListener('click',async e=>{const b=e.target.closest('[data-os-decision]');if(!b)return;b.disabled=true;try{await osRequest('os-queue-decision',{vacancyId:b.dataset.id,decision:b.dataset.osDecision});await refresh();status('Решение сохранено.');}catch(err){status(err.message,true);}finally{b.disabled=false;}});
function privateReset(){osPrivate=null;el('privateImport').disabled=true;el('privateConfirmed').checked=false;}
el('privateFile').addEventListener('change',privateReset);
action('privatePreview',async()=>{privateReset();const f=el('privateFile').files?.[0];if(!f||f.size>48*1024*1024)throw Error('Выберите корректный файл до 48 MiB.');const data=JSON.parse(await f.text());const info=vjaPrivateProfile.validate(data);const current=await chrome.storage.local.get(null);osPrivateHash=await PM.digest(PC.snapshot(current,{now:0}));osPrivate=data;el('privatePreviewText').hidden=false;el('privatePreviewText').textContent=`${info.name}\nФактов: ${info.facts}; CV: ${info.cv}\n\n`+data.profile.facts.map(f=>`${f.status||'UNKNOWN'} · ${f.text}`).join('\n\n');el('privateImport').disabled=false;status('Проверьте каждый факт и подтвердите импорт.');});
action('privateImport',async()=>{if(!osPrivate||!el('privateConfirmed').checked)throw Error('Сначала проверьте файл и подтвердите сведения.');const current=await chrome.storage.local.get(null);if(await PM.digest(PC.snapshot(current,{now:0}))!==osPrivateHash){privateReset();throw Error('Память изменилась после просмотра. Проверьте файл повторно.');}const envelope=await CR.seal(PC.snapshot(current,{sync:chrome.storage.sync?await chrome.storage.sync.get(null):{}}),el('privatePassword').value);await PV.save(envelope);const r=await osRequest('os-profile-import',{data:osPrivate,confirmed:true,replaceCV:el('privateReplaceCV').checked});privateReset();el('privatePassword').value='';await refresh();status(`Импорт выполнен: фактов ${r.facts}. Автоматические действия приостановлены.`);});
