/* Local-only product center. No page automation or direct employer submissions. */
'use strict';
const PC=globalThis.vjaProductCore,PV=globalThis.vjaProductStore,CR=globalThis.vjaProductCrypto,PM=globalThis.vjaProductModels,L=globalThis.vjaLearningCore;
const el=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=t=>Number(t)>0?new Date(Number(t)).toLocaleString('ru-RU'):'Дата не указана',pct=x=>Number.isFinite(x)?(x*100).toFixed(1)+'%':'—';
let storage={},summary={},applications=[],pageNo=0,loadedBackup=null,restoreFingerprint='',refreshPromise=null;
function status(text,error=false){el('status').textContent=text;el('status').dataset.error=String(error);}
async function request(op,args={}){const r=await chrome.runtime.sendMessage({type:'vjaCopilot',op,...args});if(!r?.ok)throw new Error(r?.error||'Фоновая служба не ответила. Перезагрузите расширение.');return r;}
function download(name,text,type='application/json'){const u=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),2000);}
function safeUrl(value){try{const u=new URL(value);return u.protocol==='https:'||u.protocol==='http:'?u.href:'';}catch{return '';}}
function card(title,body){return `<article class="card"><h3>${esc(title)}</h3>${body}</article>`;}
function stat(n,label){return `<div class="stat"><strong>${Number(n)||0}</strong><span>${esc(label)}</span></div>`;}
function showPage(id){if(!document.getElementById(id)?.classList.contains('page'))return;document.querySelectorAll('.page').forEach(x=>x.hidden=x.id!==id);document.querySelectorAll('nav button').forEach(b=>{if(b.dataset.page===id)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});history.replaceState(null,'','#'+id);}
function renderApps(){const term=el('appSearch').value.trim().toLowerCase(),filtered=applications.filter(a=>(a.vacancy?.title+' '+a.vacancy?.company).toLowerCase().includes(term)),pages=Math.max(1,Math.ceil(filtered.length/25));pageNo=Math.min(pageNo,pages-1);el('pageInfo').textContent=`${pageNo+1} / ${pages} · ${filtered.length} откликов`;el('prevPage').disabled=pageNo===0;el('nextPage').disabled=pageNo>=pages-1;el('appList').innerHTML=filtered.slice(pageNo*25,(pageNo+1)*25).map(a=>{const url=safeUrl(a.vacancy?.url);return card(a.vacancy?.title||'Отклик',`<p>${esc(a.vacancy?.company||'')}</p><span class="pill">${esc(a.status||'Unknown')}</span><span class="muted">${esc(fmt(a.updatedAt))}</span><div class="actions"><button data-timeline="${esc(a.id)}">Журнал</button>${url?`<a target="_blank" rel="noopener" href="${esc(url)}">Вакансия ↗</a>`:''}</div>`);}).join('')||'<p>Сохранённых откликов нет.</p>';}
function renderQuality(){const pref=PC.datasetQuality(L.datasetRows(summary.events)),eng=PC.datasetQuality(L.engagementDatasetRows(summary.events),'labelEmployerEngagement');el('quality').innerHTML=[['Предпочтения',pref],['Реакции работодателей',eng]].map(([name,q])=>card(name,`<div class="stats">${stat(q.n,'Размечено')}${stat(q.labels[1],'Положительных')}${stat(q.labels[0],'Отрицательных')}${stat(q.unique,'Уникальных')}</div><p class="${q.ready?'ok':'warn'} pill">${q.ready?'Минимальные проверки пройдены; качество модели ещё не оценено':'Обучение требует проверки данных'}</p><p>${q.issues.map(esc).join(' · ')||'Прежде чем активировать модель, сравните её на отложенной выборке.'}</p>`)).join('');const sig=L.deriveSignals(summary.events);el('preferences').innerHTML=Object.entries(sig.roleWeights||{}).map(([k,v])=>`<span class="pill ${v>=0?'ok':'warn'}">${esc(k)}: ${v.toFixed(1)}</span>`).join('')||'<p>Пока нет решений.</p>';}
function renderModels(){const reg=storage.vjaModelRegistryV1||{},models=PC.compareModels(reg);el('modelList').innerHTML=models.length?'<div class="card table-wrap"><table><thead><tr><th>Версия</th><th>Тип</th><th>Статус</th><th>Test n</th><th>F1</th><th>Brier</th></tr></thead><tbody>'+models.map(m=>`<tr><td>${esc(m.version)}</td><td>${esc(m.kind)}</td><td>${esc(m.status)}${m.real?'':' · test-only'}</td><td>${m.n}</td><td>${pct(m.f1)}</td><td>${m.brier===null?'—':m.brier.toFixed(3)}</td></tr>`).join('')+'</tbody></table></div>':'<p>Модель ещё не импортирована. Это не мешает обычной работе с правилами.</p>';const select=el('shadowModel');select.replaceChildren(new Option('Отключён',''));for(const m of (reg.models||[]).filter(x=>x.modelType==='personal-vacancy-logreg'))select.add(new Option(m.modelVersion,m.modelVersion));select.value=storage.vjaProductSettingsV1?.shadowModel||'';const sm=PM.shadowMetrics(storage.vjaShadowPredictionsV1||[],summary.events,select.value);el('shadowMetrics').textContent=select.value?`Проверено последующими решениями: ${sm.n}. Shadow accuracy: ${pct(sm.modelAccuracy)}; rules accuracy: ${pct(sm.rulesAccuracy)}. Это наблюдательная оценка, не причинный эксперимент.`:'Теневое сравнение отключено.';el('rollbackPreference').disabled=!reg.previousModels?.preference;el('rollbackEngagement').disabled=!reg.previousModels?.engagement;}
async function renderVault(){try{const items=await PV.list();el('vaultList').innerHTML=items.map(x=>`<p>${esc(fmt(x.createdAt))} · ${(x.bytes/1024).toFixed(0)} KiB <button data-vault-download="${esc(x.id)}">Скачать</button> <button data-vault-delete="${esc(x.id)}">Удалить копию</button></p>`).join('')||'Сохранённых checkpoints нет.';}catch(e){el('vaultList').textContent=e.message;}}
async function refresh(){if(refreshPromise)return refreshPromise;refreshPromise=(async()=>{storage=await chrome.storage.local.get(null);summary=PC.summarize(storage);let workerError='';try{applications=(await request('applications')).applications||[];}catch(e){applications=summary.jobs.map(j=>({id:j.plan?.id,vacancy:j.context?.vacancy,status:j.context?.status,updatedAt:j.context?.updatedAt,timeline:j.context?.timeline}));workerError=e.message;}el('stats').innerHTML=stat(summary.intel.length,'Проанализировано')+stat(summary.ready.length,'В очереди')+stat(summary.jobs.length,'Откликов в памяти')+stat(summary.events.length,'Событий обучения');const w=PC.weekly(storage);el('weekly').innerHTML=`<p class="muted">${esc(fmt(w.start))} — ${esc(fmt(w.end))}</p><div class="stats">${stat(w.analyzed,'Анализов')}${stat(w.applied,'Откликов')}${stat(w.saved,'Сохранено')}${stat(w.corrections,'Правок ответов')}</div>`;renderApps();renderQuality();renderModels();el('queueList').innerHTML=summary.ready.slice(0,100).map(r=>card(r.vacancy?.title||'Вакансия',`<span class="pill">${Math.round(r.fit.score)} / 100 Fit</span> <span class="pill ok">✓ Звонки не найдены в описании</span><p>${esc(r.vacancy?.company||'')}</p>${safeUrl(r.vacancy?.url)?`<a href="${esc(safeUrl(r.vacancy.url))}" target="_blank" rel="noopener">Открыть вакансию ↗</a>`:''}`)).join('')||'<p>Проанализируйте страницу HH. Сейчас подходящих результатов в памяти нет.</p>';const d=PC.diagnostics(storage,chrome.runtime.getManifest(),{indexedDB:!!globalThis.indexedDB,webCrypto:!!crypto.subtle});el('diagnosticText').textContent=JSON.stringify(d,null,2);const p=storage.vjaCandidateTruthProfile||{};el('onboarding').innerHTML=[['Профиль',!!p.fullName],['Подтверждённые факты',(p.facts||[]).some(f=>f.status==='CONFIRMED')],['Резюме',!!(storage.cvVaultRu||storage.cvVaultEn)],['Предпочтения',!!storage.vjaJobPreferencesV1]].map(([label,ok])=>card(label,`<p class="pill ${ok?'ok':'warn'}">${ok?'✓ Настроено':'! Требует настройки'}</p>`)).join('');await renderVault();el('updated').textContent='Обновлено '+new Date().toLocaleTimeString('ru-RU');status(workerError||'Данные загружены с этого устройства.',!!workerError);})().finally(()=>refreshPromise=null);return refreshPromise;}
function action(id,fn){el(id).addEventListener('click',async()=>{const b=el(id);b.disabled=true;try{await fn();}catch(e){status(e.message,true);}finally{if(id!=='confirmRestore')b.disabled=false;}});}
document.querySelectorAll('nav button').forEach(b=>b.addEventListener('click',()=>showPage(b.dataset.page)));action('refresh',refresh);el('appSearch').addEventListener('input',()=>{pageNo=0;renderApps();});el('prevPage').addEventListener('click',()=>{pageNo--;renderApps();});el('nextPage').addEventListener('click',()=>{pageNo++;renderApps();});
el('appList').addEventListener('click',e=>{const id=e.target.closest('[data-timeline]')?.dataset.timeline;if(!id)return;const a=applications.find(x=>x.id===id);el('timeline').innerHTML=(a?.timeline||[]).slice().reverse().slice(0,150).map(t=>`<div class="timeline-item"><time>${esc(fmt(t.at||t.timestamp))}</time><strong>${esc(t.title||t.label||t.type||'Событие')}</strong><p>${esc(t.note||t.message||'')}</p></div>`).join('')||'Нет сохранённых событий для этого отклика.';});
action('weeklyExport',async()=>{download('violetta-weekly-report.json',JSON.stringify(PC.weekly(await chrome.storage.local.get(null)),null,2));status('Отчёт создан.');});
action('diagnosticExport',async()=>{download('violetta-diagnostics.json',el('diagnosticText').textContent);status('Диагностика создана без содержимого профиля.');});
action('saveShadow',async()=>{await request('product-model-shadow',{version:el('shadowModel').value});await refresh();status('Shadow Mode сохранён. Fit не изменяется теневой моделью.');});
for(const [id,kind] of [['rollbackPreference','preference'],['rollbackEngagement','engagement']])action(id,async()=>{if(!confirm('Вернуть предыдущую '+kind+' модель?'))return;await request('product-model-rollback',{kind});await refresh();status('Предыдущая модель восстановлена.');});
async function makeBackup(){return CR.seal(PC.snapshot(await chrome.storage.local.get(null),{includeCV:el('includeCV').checked}),el('backupPassword').value);}
action('backupDownload',async()=>{const b=await makeBackup();download(`violetta-${new Date().toISOString().slice(0,10)}.vja`,JSON.stringify(b));el('backupPassword').value='';status('Защищённая копия создана. Сохраните пароль отдельно.');});
action('backupLocal',async()=>{await PV.save(await makeBackup());el('backupPassword').value='';await renderVault();status('Зашифрованный checkpoint сохранён в IndexedDB.');});
action('previewRestore',async()=>{loadedBackup=null;el('confirmRestore').disabled=true;const f=el('backupFile').files?.[0];if(!f)throw new Error('Выберите .vja файл.');if(f.size>48*1024*1024)throw new Error('Файл слишком большой.');const raw=JSON.parse(await f.text()),data=await CR.open(raw,el('restorePassword').value);const current=await chrome.storage.local.get(null),plan=PC.restorePlan(data,current);restoreFingerprint=await PM.digest(PC.snapshot(current,{now:0}));loadedBackup=data;el('restorePreview').textContent=`Ключей: ${plan.keyCount}; новых: ${plan.added.length}; отличающихся: ${plan.conflicts.length}. Дата: ${fmt(data.createdAt)}. Будут восстановлены только данные; автоматическая отправка отключена.`;el('confirmRestore').disabled=false;status('Файл проверен. Для применения нужно подтверждение.');});
action('confirmRestore',async()=>{if(!loadedBackup)throw new Error('Сначала проверьте файл.');if(!confirm('Заменить соответствующие локальные данные этой копией? Перед этим будет создан зашифрованный checkpoint.')){el('confirmRestore').disabled=false;return;}const current=await chrome.storage.local.get(null);if(await PM.digest(PC.snapshot(current,{now:0}))!==restoreFingerprint){loadedBackup=null;throw new Error('Данные изменились после проверки. Проверьте backup заново.');}
// Explicit checkpoint before writing. No automatic delete, no tabs opened, no sends.
await PV.save(await CR.seal(PC.snapshot(current),el('restorePassword').value));const result=await request('product-restore',{data:loadedBackup});loadedBackup=null;el('restorePassword').value='';el('restorePreview').textContent=`Восстановлено ${result.restored} ключей. Обновите страницы HH. Модели нужно включить вручную.`;await refresh();status('Восстановление выполнено; автоматические действия не запускались.');});
el('vaultList').addEventListener('click',async e=>{try{const downloadId=e.target.closest('[data-vault-download]')?.dataset.vaultDownload,deleteId=e.target.closest('[data-vault-delete]')?.dataset.vaultDelete;if(downloadId){download('violetta-checkpoint.vja',JSON.stringify(await PV.read(downloadId)));}if(deleteId&&confirm('Удалить только эту копию из локального vault?')){await PV.remove(deleteId);await renderVault();}}catch(err){status(err.message,true);}});
// Deliberately no auto-refresh during restore review; avoid changing values under confirmation.
showPage(location.hash.slice(1)||'overview');void refresh().catch(e=>status(e.message,true));
