/* Password-protected backup files. Active Chrome storage is NOT encrypted by this module. */
(function(root,factory){const api=factory(root);if(typeof module==='object'&&module.exports)module.exports=api;if(root)root.vjaProductCrypto=api;})(globalThis,function(root){
  'use strict';const ITERATIONS=310000,MAX=48*1024*1024,enc=new TextEncoder(),dec=new TextDecoder();
  const cryptoApi=()=>root.crypto||(typeof require==='function'?require('node:crypto').webcrypto:null);
  function b64(b){let x='';for(let i=0;i<b.length;i+=32768)x+=String.fromCharCode(...b.subarray(i,i+32768));return btoa(x);}
  function un64(s){if(typeof s!=='string'||s.length>MAX||!(/^[A-Za-z0-9+/]*={0,2}$/).test(s))throw new Error('Некорректный шифрованный файл.');return Uint8Array.from(atob(s),x=>x.charCodeAt(0));}
  async function key(password,salt,iterations){const c=cryptoApi();if(!c?.subtle)throw new Error('Web Crypto недоступен.');const material=await c.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveKey']);return c.subtle.deriveKey({name:'PBKDF2',salt,iterations,hash:'SHA-256'},material,{name:'AES-GCM',length:256},false,['encrypt','decrypt']);}
  async function seal(payload,password){if(typeof password!=='string'||password.length<12)throw new Error('Пароль: минимум 12 символов.');const plain=enc.encode(JSON.stringify(payload));if(plain.length>32*1024*1024)throw new Error('Backup слишком большой.');const c=cryptoApi(),salt=c.getRandomValues(new Uint8Array(16)),iv=c.getRandomValues(new Uint8Array(12)),k=await key(password,salt,ITERATIONS);const cipher=await c.subtle.encrypt({name:'AES-GCM',iv,additionalData:enc.encode('violetta-vault-v1')},k,plain);return {format:'violetta-encrypted-backup',schemaVersion:1,kdf:'PBKDF2-SHA256',iterations:ITERATIONS,cipher:'AES-256-GCM',salt:b64(salt),iv:b64(iv),data:b64(new Uint8Array(cipher))};}
  async function open(envelope,password){if(envelope?.format!=='violetta-encrypted-backup'||envelope.schemaVersion!==1||envelope.kdf!=='PBKDF2-SHA256'||envelope.cipher!=='AES-256-GCM'||!Number.isInteger(envelope.iterations)||envelope.iterations<100000||envelope.iterations>1000000)throw new Error('Неизвестный формат зашифрованной копии.');const salt=un64(envelope.salt),iv=un64(envelope.iv),bytes=un64(envelope.data);if(salt.length!==16||iv.length!==12||bytes.length<16)throw new Error('Повреждённый шифрованный файл.');try{const k=await key(password,salt,envelope.iterations),plain=await cryptoApi().subtle.decrypt({name:'AES-GCM',iv,additionalData:enc.encode('violetta-vault-v1')},k,bytes);return JSON.parse(dec.decode(plain));}catch{throw new Error('Неверный пароль или повреждённый файл.');}}
  return {ITERATIONS,seal,open};
});
