const test=require('node:test');
const assert=require('node:assert/strict');
globalThis.vjaQuestionnaireCore=require('./questionnaire-core.js');
const E=require('./questionnaire-answer-engine.js');
function profile(extra={}){return {
 fullName:'Violetta Nicolaou',firstName:'Violetta',lastName:'Nicolaou',location:'Volzhsky, Russia',contacts:{email:'violettanicolaou@gmail.com',telegram:'@Violet111',phone:''},
 facts:[
  {id:'project-dental',kind:'project',status:'CONFIRMED',roles:['developer','technical_support'],topics:['dotnet','sql','api','crm'],text:'В DentalClinic для реального заказчика разработала платформу с онлайн-записью, личным кабинетом, CRM и админ-панелью на ASP.NET Core и SQL Server.',textRu:'В DentalClinic для реального заказчика разработала платформу с онлайн-записью, личным кабинетом, CRM и админ-панелью на ASP.NET Core и SQL Server.'},
  {id:'project-route',kind:'project',status:'CONFIRMED',roles:['developer','technical_support'],topics:['php','javascript','testing'],text:'В Smart Route Planner разработала PWA на PHP и JavaScript с маршрутизацией OSRM и автоматизированными тестами.',textRu:'В Smart Route Planner разработала PWA на PHP и JavaScript с маршрутизацией OSRM и автоматизированными тестами.'},
  {id:'language-ru-en-el',kind:'language',status:'CONFIRMED',roles:['technical_support'],topics:['english','communication'],text:'Свободно владею русским, английским и греческим языками.',textRu:'Свободно владею русским, английским и греческим языками.'},
  {id:'exp-translator',kind:'experience',status:'CONFIRMED',roles:['customer_support'],topics:['translation','communication'],text:'С января 2019 года занимаюсь письменным и устным переводом для частных клиентов и международной коммуникацией.',textRu:'С января 2019 года занимаюсь письменным и устным переводом для частных клиентов и международной коммуникацией.'},
  {id:'support-task',kind:'task',status:'CONFIRMED',roles:['technical_support'],topics:['support','bugs','documentation'],text:'Проверяю исправления и обновления, документирую технические проблемы и работаю с разработчиками над их устранением.',textRu:'Проверяю исправления и обновления, документирую технические проблемы и работаю с разработчиками над их устранением.'},
  {id:'skill-csharp',kind:'skill',status:'CONFIRMED',roles:['technical_support','developer'],topics:['c#'],text:'C#',textRu:'C#'},
  {id:'education-top',kind:'education',status:'CONFIRMED',roles:['technical_support'],topics:['education'],text:'Окончила Академию ТОП по специальности «Информационные системы и программирование», диплом с отличием.',textRu:'Окончила Академию ТОП по специальности «Информационные системы и программирование», диплом с отличием.'}
 ],...extra};}
const ctx={role:'technical_support',vacancy:{vacancyId:'784',title:'Специалист технической поддержки',company:'Evercode Lab',description:'Техническая поддержка пользователей, тикеты и API.'}};

test('projects answer uses confirmed projects',()=>{const r=E.decide({question:'Есть ли у вас опыт работы с проектами? Если да, с какими проектами?',field:{type:'textarea'},profile:profile(),context:ctx});assert.equal(r.action,'fill');assert.match(r.value,/DentalClinic/);assert.match(r.value,/Smart Route Planner/);});
test('English answer uses confirmed language evidence',()=>{const r=E.decide({question:'Какой у вас уровень английского? Как применяли его в работе?',field:{type:'textarea'},profile:profile(),context:ctx});assert.equal(r.action,'fill');assert.match(r.value,/английск/i);assert.match(r.value,/международ/i);});
test('salary without confirmed amount gets a neutral human draft that still requires review',()=>{const r=E.decide({question:'Какие условия по зарплате рассматриваете?',field:{type:'textarea'},profile:profile(),context:ctx});assert.equal(r.action,'fill');assert.equal(r.category,'SALARY');assert.equal(r.source,'human-fallback');assert.equal(r.requiresReview,true);assert.match(r.value,/обсудить|discuss/i);});
test('confirmed salary can be auto-filled',()=>{const r=E.decide({question:'Какие условия по зарплате рассматриваете?',field:{type:'textarea'},profile:profile({salaryExpectation:'120 000–150 000 ₽'}),context:ctx});assert.equal(r.action,'fill');assert.match(r.value,/120/);});
test('legal consent is never invented',()=>{const r=E.decide({question:'Согласны на обработку персональных данных?',field:{type:'checkbox'},profile:profile(),context:ctx});assert.equal(r.action,'review');assert.equal(r.category,'CONSENT');});
test('confirmed questionnaire memory can be reused for a generic question',()=>{const r=E.decide({question:'Какой уровень английского?',field:{type:'textarea'},profile:profile(),context:ctx,memoryEntry:{userConfirmed:true,answer:'Английский — свободный.',vacancyKey:'',evidenceIds:['language-ru-en-el']}});assert.equal(r.action,'fill');assert.equal(r.source,'confirmed-question-memory');});
test('vacancy-specific confirmed memory is not reused for another vacancy',()=>{const r=E.decide({question:'Почему именно наша компания?',field:{type:'textarea'},profile:profile(),context:{...ctx,vacancy:{...ctx.vacancy,vacancyId:'999'}},memoryEntry:{userConfirmed:true,answer:'Старый ответ.',vacancyKey:'784'}});assert.notEqual(r.source,'confirmed-question-memory');});
test('support experience is grounded in support facts',()=>{const r=E.decide({question:'Расскажите об опыте технической поддержки',field:{type:'textarea'},profile:profile(),context:ctx});assert.equal(r.action,'fill');assert.match(r.value,/техническ|документир/i);});

test('numeric salary field still stays unresolved when no amount is confirmed',()=>{const r=E.decide({question:'Ожидаемая зарплата',field:{type:'number'},profile:profile(),context:ctx});assert.equal(r.action,'review');assert.equal(r.category,'SALARY');});
test('unknown free-text question gets a neutral draft without invented facts',()=>{const r=E.decide({question:'Расскажите что-нибудь ещё, что считаете важным',field:{type:'textarea'},profile:profile(),context:ctx});assert.equal(r.action,'fill');assert.equal(r.source,'human-fallback');assert.equal(r.requiresReview,true);assert.match(r.value,/интервью|interview/i);});
test('missing technical evidence can use a reviewable human draft',()=>{const r=E.decide({question:'Есть ли опыт с Kubernetes?',field:{type:'textarea'},profile:{...profile(),facts:profile().facts.filter(f=>f.kind!=='skill'&&f.kind!=='task')},context:ctx});assert.equal(r.action,'fill');assert.equal(r.requiresReview,true);assert.equal(r.source,'human-fallback');});
